import { savePage } from "@/app/admin/actions";
import { EmptyState, PageHeader, StatusBadge } from "@/components/admin/AdminPrimitives";
import { hasDatabaseUrl, prisma } from "@/lib/db/client";

export default async function PagesAdminPage() {
  if (!hasDatabaseUrl()) return <section className="admin-content"><PageHeader eyebrow="CONTENT / PAGES" title="Pages" description="Pages, sections and revisions are ready for CMS use once DATABASE_URL is configured." /><EmptyState title="Database not configured" description="The source-backed public pages remain the intentional parity fallback." /></section>;
  const pages = await prisma.page.findMany({ where: { slug: { not: "home" } }, include: { sections: { where: { type: "richText" }, take: 1 }, revisions: { orderBy: { createdAt: "desc" }, take: 1 } }, orderBy: { slug: "asc" } });
  return <section className="admin-content"><PageHeader eyebrow="CONTENT / PAGES" title="Pages" description="Each save creates a revision. The editorial body becomes authoritative only when the page is published and valid content exists." /><div className="admin-page-editor-list">{pages.length ? pages.map((page) => { const body = page.sections[0]?.content as { body?: string; approachHeading?: string; approachBody?: string } | undefined; return <form action={savePage} className="admin-card admin-content-form" key={page.id}><div className="admin-record-title"><h2>{page.slug}</h2><StatusBadge value={page.status} /></div><input type="hidden" name="id" value={page.id} /><label>Page headline<input name="title" defaultValue={page.title} required /></label><label>Editorial body <small>Public introduction</small><textarea name="body" rows={5} defaultValue={body?.body ?? ""} /></label><label>Secondary heading / CTA heading<input name="approachHeading" defaultValue={body?.approachHeading ?? ""} /></label><label>Secondary body<textarea name="approachBody" rows={5} defaultValue={body?.approachBody ?? ""} /></label><div className="admin-form-columns"><label>SEO title<input name="seoTitle" defaultValue={page.seoTitle ?? ""} /></label><label>Publish state<select name="status" defaultValue={page.status}><option value="DRAFT">Draft</option><option value="PUBLISHED">Published</option><option value="HIDDEN">Hidden</option></select></label></div><label>SEO description<textarea name="seoDescription" rows={3} defaultValue={page.seoDescription ?? ""} /></label><small>Last revision: {page.revisions[0]?.createdAt.toLocaleString() ?? "Not yet edited"}</small><button type="submit">Save page</button></form> }) : <EmptyState title="No pages seeded" description="Run the approved seed workflow after connecting a database." />}</div></section>;
}
