import { saveService } from "@/app/admin/actions";
import { EmptyState, PageHeader, StatusBadge } from "@/components/admin/AdminPrimitives";
import { hasDatabaseUrl, prisma } from "@/lib/db/client";

export default async function ServicesAdminPage() {
  if (!hasDatabaseUrl()) return <section className="admin-content"><PageHeader eyebrow="CONTENT / SERVICES" title="Services" description="Service content will become authoritative as soon as published CMS records are available." /><EmptyState title="Database not configured" description="Set DATABASE_URL to manage the service catalogue." /></section>;
  const services = await prisma.service.findMany({ orderBy: { updatedAt: "desc" }, take: 50 });
  return <section className="admin-content"><PageHeader eyebrow="CONTENT / SERVICES" title="Services" description="Use one line per capability in the description field; public pages retain their existing editorial layout." /><div className="admin-editor-grid"><form action={saveService} className="admin-card admin-content-form"><h2>New service</h2><label>Title<input name="title" required /></label><label>Slug<input name="slug" required placeholder="image-post-production" /></label><label>Short label / category<input name="category" required /></label><label>Summary<textarea name="shortDescription" required rows={4} /></label><label>Capabilities <small>One per line</small><textarea name="description" rows={6} /></label><label>Publishing<select name="status" defaultValue="DRAFT"><option value="DRAFT">Draft</option><option value="PUBLISHED">Published</option><option value="ARCHIVED">Archived</option></select></label><button type="submit">Save service</button></form><div className="admin-card"><h2>Existing services</h2>{services.length ? <div className="admin-record-list">{services.map((service) => <article key={service.id}><div><strong>{service.title}</strong><span>/{service.slug} · {service.category}</span></div><StatusBadge value={service.status} /></article>)}</div> : <EmptyState title="No services yet" description="Create a service draft to begin." />}</div></div></section>;
}
