import Image from "next/image";
import { uploadMedia } from "@/app/admin/actions";
import { EmptyState, PageHeader, StatusBadge } from "@/components/admin/AdminPrimitives";
import { hasDatabaseUrl, prisma } from "@/lib/db/client";

export default async function MediaAdminPage() {
  if (!hasDatabaseUrl()) return <section className="admin-content"><PageHeader eyebrow="ASSET LIBRARY" title="Media" description="Media uses the configured Cloudinary provider; uploads are never simulated." /><EmptyState title="Database not configured" description="Set DATABASE_URL and Cloudinary credentials before uploading approved assets." /></section>;
  const media = await prisma.media.findMany({ orderBy: { createdAt: "desc" }, take: 60 }); const storageReady = Boolean(process.env.CLOUDINARY_CLOUD_NAME && process.env.CLOUDINARY_API_KEY && process.env.CLOUDINARY_API_SECRET);
  return <section className="admin-content"><PageHeader eyebrow="ASSET LIBRARY" title="Media" description="Approved source assets only. Files retain their original aspect ratio; use captions and alt text in the contextual editor." />{!storageReady && <p className="admin-notice">Cloudinary storage is not configured. Upload controls remain disabled by the provider.</p>}<div className="admin-editor-grid"><form action={uploadMedia} className="admin-card admin-content-form"><h2>Upload asset</h2><label>File<input name="file" type="file" accept="image/jpeg,image/png,image/webp,image/avif,video/mp4,video/webm" required /></label><small>JPEG, PNG, WebP, AVIF, MP4 or WebM · max 200 MB</small><button type="submit">Upload to library</button></form><div className="admin-card"><h2>Latest media</h2>{media.length ? <div className="admin-media-grid">{media.map((item) => <article key={item.id}>{item.mediaType === "IMAGE" ? <Image src={item.publicUrl} alt={item.alt || item.filename} width={240} height={160} unoptimized /> : <div className="admin-media-video">VIDEO</div>}<strong>{item.filename}</strong><span>{item.mimeType}</span><StatusBadge value={item.mediaType} /></article>)}</div> : <EmptyState title="No media uploaded" description="Upload approved images or videos once Cloudinary is configured." />}</div></div></section>;
}
