import Link from "next/link";
import { Prisma } from "@prisma/client";
import { EmptyState, PageHeader, StatusBadge } from "@/components/admin/AdminPrimitives";
import { hasDatabaseUrl, prisma } from "@/lib/db/client";
export default async function EnquiriesAdminPage({ searchParams }: { searchParams: Promise<{ q?: string; status?: string; page?: string; archived?: string }> }) {
  if (!hasDatabaseUrl()) return <EmptyState title="Database not configured" description="Connect the database to manage enquiries." />;
  const params = await searchParams; const q = (params.q ?? "").slice(0, 200); const page = Math.max(1, Math.min(10000, Number(params.page) || 1)); const status = ["NEW", "IN_PROGRESS", "REPLIED", "CLOSED"].includes(params.status ?? "") ? params.status as "NEW" : undefined;
  const where: Prisma.ContactSubmissionWhereInput = { archivedAt: params.archived === "true" ? { not: null } : null, ...(status ? { status } : {}), ...(q ? { OR: ["name", "email", "company", "message"].map((field) => ({ [field]: { contains: q, mode: "insensitive" } })) } : {}) };
  const [enquiries, count] = await Promise.all([prisma.contactSubmission.findMany({ where, orderBy: { createdAt: "desc" }, take: 20, skip: (page - 1) * 20 }), prisma.contactSubmission.count({ where })]);
  const href = (number: number) => `/admin/enquiries?${new URLSearchParams({ q, status: params.status ?? "", archived: params.archived ?? "", page: String(number) })}`;
  return <section className="admin-content"><PageHeader eyebrow="CRM" title="Enquiries" description="Review project briefs, record follow-ups and manage each enquiry." /><form className="admin-card admin-filter-row"><label>Search<input name="q" defaultValue={q} placeholder="Name, email, company or brief" /></label><label>Status<select name="status" defaultValue={status ?? ""}><option value="">All statuses</option><option value="NEW">New</option><option value="IN_PROGRESS">In review</option><option value="REPLIED">Contacted</option><option value="CLOSED">Closed</option></select></label><label>View<select name="archived" defaultValue={params.archived ?? "false"}><option value="false">Active enquiries</option><option value="true">Archived enquiries</option></select></label><button>Filter</button></form><div className="admin-card">{enquiries.length ? <div className="admin-record-list">{enquiries.map((item) => <article key={item.id}><div><Link href={`/admin/enquiries/${item.id}`}><strong>{item.name}</strong></Link><span>{item.email}{item.company ? ` · ${item.company}` : ""}</span><small>{item.createdAt.toLocaleString()}</small></div><StatusBadge value={item.status} /></article>)}</div> : <EmptyState title="No enquiries found" description="New website enquiries will appear here. Adjust filters to find archived records." />}<div className="admin-inline-actions">{page > 1 && <Link href={href(page - 1)}>Previous</Link>}<span>{count} enquiries · Page {page}</span>{page * 20 < count && <Link href={href(page + 1)}>Next</Link>}</div></div></section>;
}
