import { saveProject } from "@/app/admin/actions";
import { EmptyState, PageHeader } from "@/components/admin/AdminPrimitives";
import { ProjectAdminList, projectAdminWhere, type ProjectAdminFilter } from "@/components/admin/ProjectAdminList";
import { hasDatabaseUrl, prisma } from "@/lib/db/client";

export default async function ProjectsAdminPage({ searchParams }: { searchParams: Promise<{ filter?: string }> }) {
  if (!hasDatabaseUrl()) return <section className="admin-content"><PageHeader eyebrow="CONTENT / WORK" title="Projects" description="Connect the database to manage the portfolio. Public work remains on its intentional parity fallback until then." /><EmptyState title="Database not configured" description="No project data can be created until DATABASE_URL is configured." /></section>;
  const raw = (await searchParams).filter; const filter: ProjectAdminFilter = ["ALL", "WORK", "CASE_STUDIES", "DRAFT", "PUBLISHED", "ARCHIVED"].includes(raw ?? "") ? raw as ProjectAdminFilter : "ALL";
  const projects = await prisma.project.findMany({ where: projectAdminWhere(filter), include: { thumbnailMedia: true, heroMedia: true }, orderBy: [{ updatedAt: "desc" }, { title: "asc" }], take: 100 });
  return <section className="admin-content"><PageHeader eyebrow="CONTENT / WORK + CASE STUDIES" title="Projects" description="One Project record powers Work and, when enabled, the deeper Case Study presentation." /><div className="admin-editor-grid"><form action={saveProject} className="admin-card admin-content-form"><h2>New project draft</h2><label>Title<input name="title" required /></label><label>Slug<input name="slug" required placeholder="campaign-name" /></label><label>Category<input name="category" required placeholder="Product, Beauty, Fashion…" /></label><label>Summary<textarea name="summary" required rows={4} /></label><label>Services <small>Optional, comma-separated</small><input name="services" /></label><input name="status" type="hidden" value="DRAFT" /><input name="featured" type="hidden" value="false" /><label className="admin-check"><input name="featured" type="checkbox" value="true" /> Feature in Selected Work</label><input name="isCaseStudy" type="hidden" value="false" /><label className="admin-check"><input name="isCaseStudy" type="checkbox" value="true" /> Prepare as a Case Study</label><button name="intent" value="draft">Create draft</button></form><div className="admin-card"><h2>Existing projects</h2><ProjectAdminList projects={projects} filter={filter} /></div></div></section>;
}
