import Link from "next/link";
import { saveProject } from "@/app/admin/actions";
import { EmptyState, PageHeader, StatusBadge } from "@/components/admin/AdminPrimitives";
import { hasDatabaseUrl, prisma } from "@/lib/db/client";

export default async function ProjectsAdminPage() {
  if (!hasDatabaseUrl()) return <section className="admin-content"><PageHeader eyebrow="CONTENT / WORK" title="Projects" description="Connect the database to manage the portfolio. Public work remains on its intentional parity fallback until then." /><EmptyState title="Database not configured" description="No project data can be created until DATABASE_URL is configured." /></section>;
  const projects = await prisma.project.findMany({ orderBy: { updatedAt: "desc" }, take: 50 });
  return <section className="admin-content"><PageHeader eyebrow="CONTENT / WORK" title="Projects" description="Published projects immediately power /work and their matching public case-study route." /><div className="admin-editor-grid"><form action={saveProject} className="admin-card admin-content-form"><h2>New project</h2><label>Title<input name="title" required /></label><label>Slug<input name="slug" required placeholder="campaign-name" /></label><label>Category<input name="category" required placeholder="Product, Beauty, Fashion…" /></label><label>Summary<textarea name="summary" required rows={4} /></label><label>Services <small>Comma-separated</small><input name="services" /></label><label>Publishing<select name="status" defaultValue="DRAFT"><option value="DRAFT">Draft</option><option value="PUBLISHED">Published</option><option value="ARCHIVED">Archived</option></select></label><input name="featured" type="hidden" value="false" /><label className="admin-check"><input name="featured" type="checkbox" value="true" /> Feature on home</label><button type="submit">Save project</button></form><div className="admin-card"><h2>Existing projects</h2>{projects.length ? <div className="admin-record-list">{projects.map((project) => <article key={project.id}><div><strong>{project.title}</strong><span>/{project.slug} · {project.category}</span></div><StatusBadge value={project.status} /><Link href={`/admin/projects/${project.id}`}>Edit</Link><Link href={`/work/${project.slug}`} target="_blank">Preview ↗</Link></article>)}</div> : <EmptyState title="No projects yet" description="Create a draft, then publish it when its public copy is ready." />}</div></div></section>;
}
