import Link from "next/link";
import { notFound } from "next/navigation";
import { prisma } from "@/lib/db/client";
import { saveEnquiry } from "@/app/admin/actions";
import { PageHeader } from "@/components/admin/AdminPrimitives";
import { isSafeHref } from "@/lib/validation/site";
export default async function EnquiryDetail({ params }: { params: Promise<{ id: string }> }) {
  const id = (await params).id; const item = await prisma.contactSubmission.findUnique({ where: { id } }); if (!item) notFound();
  const history = await prisma.auditLog.findMany({ where: { entityType: "ContactSubmission", entityId: id }, orderBy: { createdAt: "desc" }, take: 30 });
  return <section className="admin-content"><PageHeader eyebrow="CRM / ENQUIRY" title={item.name} description={`Received ${item.createdAt.toLocaleString()}`} /><Link href="/admin/enquiries">← All enquiries</Link><div className="admin-card"><dl className="admin-enquiry-details">{[["Email", item.email], ["Company", item.company], ["Project type", item.projectType], ["Volume", item.estimatedVolume], ["Timeline", item.timeline], ["Brief", item.message]].map(([label, value]) => value && <div key={label}><dt>{label}</dt><dd>{value}</dd></div>)}</dl><a href={`mailto:${item.email}?subject=${encodeURIComponent("Your PicVisual project enquiry")}`}>Email {item.name} ↗</a>{item.projectLink && isSafeHref(item.projectLink) && <p><a href={item.projectLink} target="_blank" rel="noopener noreferrer">Open supplied project link ↗</a></p>}</div><form action={saveEnquiry} className="admin-card admin-content-form"><input type="hidden" name="id" value={id} /><label>Status<select name="status" defaultValue={item.status}><option value="NEW">New</option><option value="IN_PROGRESS">In review</option><option value="REPLIED">Contacted</option><option value="CLOSED">Closed</option></select></label><label>Internal notes<textarea name="internalNotes" maxLength={8000} rows={8} defaultValue={item.internalNotes ?? ""} /></label><input type="hidden" name="archive" value="false" /><label className="admin-check"><input name="archive" type="checkbox" value="true" defaultChecked={!!item.archivedAt} /> Archive this enquiry</label><button>Save enquiry</button></form><div className="admin-card"><h2>Activity</h2>{history.map((event) => <p key={event.id}>{event.action.replaceAll("_", " ")} · {event.createdAt.toLocaleString()}</p>)}</div></section>;
}
