import { deleteClient, moveClient, saveClient } from "@/app/admin/actions";
import { ConfirmDeleteButton } from "@/components/admin/ConfirmDeleteButton";
import { EmptyState, PageHeader, StatusBadge } from "@/components/admin/AdminPrimitives";
import { hasDatabaseUrl, prisma } from "@/lib/db/client";

export default async function ClientsAdminPage({ searchParams }: { searchParams: Promise<{ success?: string; error?: string }> }) {
  if (!hasDatabaseUrl()) return <section className="admin-content"><PageHeader eyebrow="CONTENT / CLIENTS" title="Clients" description="Client logos are managed from approved media only." /><EmptyState title="Database not configured" description="Set DATABASE_URL to manage verified client records." /></section>;
  const [items, media, feedback] = await Promise.all([prisma.client.findMany({ orderBy: { order: "asc" } }), prisma.media.findMany({ where: { mediaType: "IMAGE" }, select: { id: true, filename: true }, take: 100 }), searchParams]);
  return <section className="admin-content"><PageHeader eyebrow="CONTENT / CLIENTS" title="Clients" description="Use this only for verified client names, URLs, and approved logos. Empty collections stay hidden publicly." />{(feedback.success || feedback.error) && <p className="admin-feedback" role="status">{feedback.success ? `Saved: ${feedback.success.replace(/-/g, " ")}.` : `Could not save: ${feedback.error?.replace(/-/g, " ")}.`}</p>}<div className="admin-editor-grid"><form action={saveClient} className="admin-card admin-content-form"><h2>Add client</h2><label>Client name<input name="name" required /></label><label>Website<input name="website" type="url" placeholder="https://…" /></label><label>Logo<select name="logoMediaId"><option value="">No logo</option>{media.map((item) => <option key={item.id} value={item.id}>{item.filename}</option>)}</select></label><input type="hidden" name="enabled" value="false" /><label className="admin-check"><input name="enabled" type="checkbox" value="true" defaultChecked /> Visible</label><button type="submit">Save client</button></form><div className="admin-card"><h2>Verified clients</h2>{items.length ? <div className="admin-record-list">{items.map((item, index) => <article key={item.id}><div><strong>{item.name}</strong><span>{item.website || "No website"} · Order {item.order + 1} · {item.logoMediaId ? "Logo selected" : "No logo"}</span></div><StatusBadge value={item.enabled ? "ACTIVE" : "HIDDEN"} /><div className="admin-inline-actions"><form action={moveClient}><input type="hidden" name="id" value={item.id} /><input type="hidden" name="direction" value="up" /><button disabled={index === 0}>Move up</button></form><form action={moveClient}><input type="hidden" name="id" value={item.id} /><input type="hidden" name="direction" value="down" /><button disabled={index === items.length - 1}>Move down</button></form><form action={deleteClient}><input type="hidden" name="id" value={item.id} /><ConfirmDeleteButton label={item.name} /></form></div><details><summary>Edit</summary><form action={saveClient} className="admin-content-form"><input type="hidden" name="id" value={item.id} /><label>Client name<input name="name" required defaultValue={item.name} /></label><label>Website<input name="website" type="url" defaultValue={item.website ?? ""} /></label><label>Logo<select name="logoMediaId" defaultValue={item.logoMediaId ?? ""}><option value="">No logo</option>{media.map((mediaItem) => <option key={mediaItem.id} value={mediaItem.id}>{mediaItem.filename}</option>)}</select></label><input type="hidden" name="enabled" value="false" /><label className="admin-check"><input name="enabled" type="checkbox" value="true" defaultChecked={item.enabled} /> Visible</label><button type="submit">Save changes</button></form></details></article>)}</div> : <EmptyState title="No clients" description="No client logos are shown publicly until verified records are added." />}</div></div></section>;
}
