import { deleteClient, saveClient } from "@/app/admin/actions";
import { EmptyState, PageHeader, StatusBadge } from "@/components/admin/AdminPrimitives";
import { hasDatabaseUrl, prisma } from "@/lib/db/client";

export default async function ClientsAdminPage() {
  if (!hasDatabaseUrl()) return <section className="admin-content"><PageHeader eyebrow="CONTENT / CLIENTS" title="Clients" description="Client logos are managed from approved media only." /><EmptyState title="Database not configured" description="Set DATABASE_URL to manage verified client records." /></section>;
  const [items, media] = await Promise.all([prisma.client.findMany({ orderBy: { order: "asc" } }), prisma.media.findMany({ where: { mediaType: "IMAGE" }, select: { id: true, filename: true }, take: 100 })]);
  return <section className="admin-content"><PageHeader eyebrow="CONTENT / CLIENTS" title="Clients" description="Use this only for verified client names, URLs, and approved logos. Empty collections stay hidden publicly." /><div className="admin-editor-grid"><form action={saveClient} className="admin-card admin-content-form"><h2>Add client</h2><label>Client name<input name="name" required /></label><label>Website<input name="website" type="url" placeholder="https://…" /></label><label>Logo<select name="logoMediaId"><option value="">No logo</option>{media.map((item) => <option key={item.id} value={item.id}>{item.filename}</option>)}</select></label><input type="hidden" name="enabled" value="false" /><label className="admin-check"><input name="enabled" type="checkbox" value="true" defaultChecked /> Visible</label><button type="submit">Save client</button></form><div className="admin-card"><h2>Verified clients</h2>{items.length ? <div className="admin-record-list">{items.map((item) => <article key={item.id}><div><strong>{item.name}</strong><span>{item.website || "No website"}</span></div><StatusBadge value={item.enabled ? "ACTIVE" : "HIDDEN"} /><form action={deleteClient}><input type="hidden" name="id" value={item.id} /><button>Delete</button></form></article>)}</div> : <EmptyState title="No clients" description="No client logos are shown publicly until verified records are added." />}</div></div></section>;
}
