import { deleteFaq, moveFaq, saveFaq } from "@/app/admin/actions";
import { EmptyState, PageHeader, StatusBadge } from "@/components/admin/AdminPrimitives";
import { hasDatabaseUrl, prisma } from "@/lib/db/client";

export default async function FaqAdminPage() {
  if (!hasDatabaseUrl()) return <section className="admin-content"><PageHeader eyebrow="CONTENT / FAQ" title="FAQ" description="The public FAQ remains safely file-backed until CMS data is available." /><EmptyState title="Database not configured" description="Set DATABASE_URL to edit the published FAQ." /></section>;
  const faq = await prisma.fAQ.findMany({ where: { pageKey: "home" }, orderBy: { order: "asc" } });
  return <section className="admin-content"><PageHeader eyebrow="CONTENT / FAQ" title="FAQ" description="Enabled entries are ordered and rendered in the homepage accordion." /><div className="admin-editor-grid"><form action={saveFaq} className="admin-card admin-content-form"><h2>New question</h2><label>Question<input name="question" required /></label><label>Answer<textarea name="answer" rows={8} required /></label><input name="enabled" type="hidden" value="false" /><label className="admin-check"><input name="enabled" type="checkbox" value="true" defaultChecked /> Show on website</label><button type="submit">Save FAQ</button></form><div className="admin-card"><h2>Published order</h2>{faq.length ? <div className="admin-record-list">{faq.map((item) => <article key={item.id}><div><strong>{item.order + 1}. {item.question}</strong><span>{item.answer}</span></div><StatusBadge value={item.enabled ? "ACTIVE" : "HIDDEN"} /><div className="admin-inline-actions"><form action={moveFaq}><input type="hidden" name="id" value={item.id} /><input type="hidden" name="direction" value="up" /><button>↑</button></form><form action={moveFaq}><input type="hidden" name="id" value={item.id} /><input type="hidden" name="direction" value="down" /><button>↓</button></form><form action={deleteFaq}><input type="hidden" name="id" value={item.id} /><button>Delete</button></form></div></article>)}</div> : <EmptyState title="No FAQ records yet" description="Create an entry to begin." />}</div></div></section>;
}
