"use client";

import { useMemo, useState } from "react";
import { useFormStatus } from "react-dom";
import { MediaPicker, type PickerMedia } from "@/components/admin/MediaPicker";

type Value = Record<string, unknown>;
type Option = { id: string; label: string; detail?: string };
type Field = { key: string; label: string; multiline?: boolean; optional?: boolean };
type MediaField = { key: string; label: string; accept: "IMAGE" | "VIDEO"; slots?: number };

const textFields: Record<string, Field[]> = {
  hero: [{ key: "eyebrow", label: "Eyebrow" }, { key: "headline", label: "Heading" }, { key: "secondaryHeadline", label: "Secondary heading", optional: true }, { key: "description", label: "Description", multiline: true }],
  positioning: [{ key: "eyebrow", label: "Eyebrow", optional: true }, { key: "headline", label: "Heading" }, { key: "highlight", label: "Highlight text", optional: true }, { key: "body", label: "Body", multiline: true }],
  capabilities: [{ key: "eyebrow", label: "Eyebrow", optional: true }, { key: "heading", label: "Heading", optional: true }, { key: "description", label: "Description", multiline: true, optional: true }],
  beforeAfter: [{ key: "eyebrow", label: "Eyebrow", optional: true }, { key: "heading", label: "Heading" }, { key: "description", label: "Description", multiline: true, optional: true }, { key: "beforeLabel", label: "Before label" }, { key: "afterLabel", label: "After label" }],
  selectedWork: [{ key: "heading", label: "Heading" }, { key: "description", label: "Description", multiline: true, optional: true }, { key: "ctaLabel", label: "CTA label", optional: true }, { key: "ctaHref", label: "CTA link", optional: true }],
  productionWorkflow: [{ key: "eyebrow", label: "Eyebrow", optional: true }, { key: "heading", label: "Heading" }, { key: "description", label: "Description", multiline: true, optional: true }],
  whyPicVisual: [{ key: "eyebrow", label: "Eyebrow", optional: true }, { key: "heading", label: "Heading" }, { key: "description", label: "Description", multiline: true, optional: true }],
  faq: [{ key: "heading", label: "Heading" }, { key: "description", label: "Description", multiline: true, optional: true }],
  cta: [{ key: "eyebrow", label: "Eyebrow" }, { key: "heading", label: "Heading" }, { key: "body", label: "Body", multiline: true }, { key: "ctaLabel", label: "CTA label" }, { key: "ctaHref", label: "CTA link" }],
  textMedia: [{ key: "heading", label: "Heading" }, { key: "body", label: "Body", multiline: true }],
  richText: [{ key: "heading", label: "Heading", optional: true }, { key: "body", label: "Body", multiline: true }],
};
const immersive = ["imagePost", "videoEdit", "motion", "product", "jewelry", "creative", "development"];
for (const type of immersive) textFields[type] = [{ key: "label", label: "Label" }, { key: "heading", label: "Heading" }, { key: "description", label: "Description", multiline: true }];
const mediaFields: Record<string, MediaField[]> = {
  hero: [{ key: "primaryMediaId", label: "Primary image", accept: "IMAGE" }, { key: "secondaryMediaId", label: "Secondary image", accept: "IMAGE" }, { key: "backgroundMediaId", label: "Background image", accept: "IMAGE" }, { key: "videoMediaId", label: "Optional video", accept: "VIDEO" }, { key: "posterMediaId", label: "Video poster", accept: "IMAGE" }, { key: "mobileMediaId", label: "Mobile media override", accept: "IMAGE" }],
  positioning: [{ key: "mediaId", label: "Optional media", accept: "IMAGE" }], capabilities: [{ key: "mediaId", label: "Supporting media", accept: "IMAGE" }],
  beforeAfter: [{ key: "beforeMediaId", label: "Before image", accept: "IMAGE" }, { key: "afterMediaId", label: "After image", accept: "IMAGE" }, { key: "detailMediaId", label: "Detail image", accept: "IMAGE" }],
  textMedia: [{ key: "mediaId", label: "Media", accept: "IMAGE" }], video: [{ key: "mediaId", label: "Video", accept: "VIDEO" }, { key: "posterMediaId", label: "Poster", accept: "IMAGE" }],
  imagePost: [{ key: "rawMediaId", label: "Raw image", accept: "IMAGE" }, { key: "finishedMediaId", label: "Finished image", accept: "IMAGE" }, { key: "detailMediaIds", label: "Detail crops", accept: "IMAGE", slots: 3 }, { key: "mobileMediaId", label: "Mobile override", accept: "IMAGE" }],
  videoEdit: [{ key: "videoMediaId", label: "Main video", accept: "VIDEO" }, { key: "posterMediaId", label: "Poster", accept: "IMAGE" }, { key: "timelineMediaIds", label: "Timeline thumbnails", accept: "IMAGE", slots: 3 }, { key: "finalFrameMediaId", label: "Final frame", accept: "IMAGE" }, { key: "mobileVideoMediaId", label: "Mobile video override", accept: "VIDEO" }],
  motion: [{ key: "reelMediaIds", label: "Reel videos", accept: "VIDEO", slots: 3 }, { key: "posterMediaIds", label: "Reel posters", accept: "IMAGE", slots: 3 }, { key: "mobileMediaId", label: "Mobile override", accept: "IMAGE" }],
  product: [{ key: "sourceMediaId", label: "Source / raw", accept: "IMAGE" }, { key: "cutoutMediaId", label: "Cutout", accept: "IMAGE" }, { key: "shadowMediaId", label: "Shadow", accept: "IMAGE" }, { key: "finalMediaId", label: "Final PDP", accept: "IMAGE" }, { key: "campaignMediaId", label: "Campaign image", accept: "IMAGE" }, { key: "mobileMediaId", label: "Mobile override", accept: "IMAGE" }],
  jewelry: [{ key: "primaryMediaId", label: "Primary jewelry image", accept: "IMAGE" }, { key: "macroMediaId", label: "Macro / detail", accept: "IMAGE" }, { key: "supportingMediaId", label: "Supporting image", accept: "IMAGE" }, { key: "mobileMediaId", label: "Mobile override", accept: "IMAGE" }],
  creative: [{ key: "backgroundMediaId", label: "Background layer", accept: "IMAGE" }, { key: "subjectMediaId", label: "Subject layer", accept: "IMAGE" }, { key: "shadowMediaId", label: "Shadow layer", accept: "IMAGE" }, { key: "lightMediaId", label: "Light layer", accept: "IMAGE" }, { key: "textureMediaId", label: "Texture layer", accept: "IMAGE" }, { key: "finalMediaId", label: "Final composite", accept: "IMAGE" }, { key: "mobileMediaId", label: "Mobile composite", accept: "IMAGE" }],
  development: [{ key: "interfaceMediaId", label: "Main interface", accept: "IMAGE" }, { key: "fragmentMediaId", label: "Secondary fragment", accept: "IMAGE" }, { key: "screenshotMediaId", label: "Screenshot", accept: "IMAGE" }, { key: "backgroundMediaId", label: "Background visual", accept: "IMAGE" }, { key: "mobileMediaId", label: "Mobile fallback", accept: "IMAGE" }],
};
function SubmitButton() { const { pending } = useFormStatus(); return <button type="submit" disabled={pending}>{pending ? "Saving…" : "Save section"}</button>; }
function ItemList({ name, value, onChange }: { name: string; value: unknown; onChange: (next: unknown) => void }) { const items = Array.isArray(value) ? value as Array<Record<string, unknown>> : []; const update = (index: number, patch: Record<string, unknown>) => onChange(items.map((item, itemIndex) => itemIndex === index ? { ...item, ...patch } : item)); const move = (index: number, direction: -1 | 1) => { const next = [...items]; const target = index + direction; if (target < 0 || target >= next.length) return; [next[index], next[target]] = [next[target], next[index]]; onChange(next); }; return <div className="admin-repeat-list"><span>{name === "steps" ? "Workflow steps" : "Value items"}</span>{items.map((entry, index) => <div className="admin-repeat-item" key={`${name}-${index}`}><input aria-label={`${name} title ${index + 1}`} value={String(entry.title ?? "")} onChange={(event) => update(index, { title: event.target.value })} placeholder="Title" /><textarea aria-label={`${name} description ${index + 1}`} value={String(entry.description ?? "")} onChange={(event) => update(index, { description: event.target.value })} placeholder="Description" /><label className="admin-check"><input type="checkbox" checked={entry.enabled !== false} onChange={(event) => update(index, { enabled: event.target.checked })} /> Visible</label><button type="button" onClick={() => move(index, -1)}>Up</button><button type="button" onClick={() => move(index, 1)}>Down</button><button type="button" onClick={() => onChange(items.filter((_, itemIndex) => itemIndex !== index))}>Remove</button></div>)}<button type="button" onClick={() => onChange([...items, { title: "", description: "", enabled: true }])}>Add {name === "steps" ? "step" : "item"}</button></div>; }

export function HomeSectionEditor({ section, media, services, projects, faqs, action }: { section: { id: string; type: string; enabled: boolean; content: unknown }; media: PickerMedia[]; services: Option[]; projects: Option[]; faqs: Option[]; action: (formData: FormData) => void }) {
  const initial = useMemo(() => ({ ...((section.content && typeof section.content === "object" ? section.content : {}) as Value) }), [section.content]);
  const [content, setContent] = useState<Value>(initial); const update = (key: string, value: unknown) => setContent((current) => ({ ...current, [key]: value }));
  const type = section.type; const fields = textFields[type] ?? []; const choices = type === "capabilities" ? services : type === "selectedWork" ? projects : type === "faq" ? faqs : [];
  const choiceKey = type === "capabilities" ? "serviceIds" : type === "selectedWork" ? "projectIds" : "faqIds";
  const selectedChoices = Array.isArray(content[choiceKey]) ? content[choiceKey] as string[] : [];
  const toggleChoice = (id: string) => update(choiceKey, selectedChoices.includes(id) ? selectedChoices.filter((current) => current !== id) : [...selectedChoices, id]);
  const ctaValue = content.cta && typeof content.cta === "object" ? content.cta as Value : {};
  const payload = { ...content, ...(type === "selectedWork" ? { cta: content.ctaLabel || content.ctaHref ? { label: String(content.ctaLabel ?? ""), href: String(content.ctaHref ?? "") } : undefined } : {}), ...(type === "cta" ? { cta: { label: String(content.ctaLabel ?? ""), href: String(content.ctaHref ?? "") } } : {}) };
  delete (payload as Value).ctaLabel; delete (payload as Value).ctaHref;
  return <form action={action} className="admin-card admin-content-form"><div className="admin-record-title"><div><span className="admin-kicker">{type}</span><h2>{type.replace(/([A-Z])/g, " $1")}</h2></div><span className="status-badge">{section.enabled ? "VISIBLE" : "HIDDEN"}</span></div><input type="hidden" name="id" value={section.id} /><input type="hidden" name="type" value={type} /><input type="hidden" name="content" value={JSON.stringify(payload)} />{fields.map((field) => <label key={field.key}>{field.label}{field.multiline ? <textarea value={String(field.key === "ctaLabel" ? ctaValue.label ?? content[field.key] ?? "" : field.key === "ctaHref" ? ctaValue.href ?? content[field.key] ?? "" : content[field.key] ?? "")} onChange={(event) => update(field.key, event.target.value)} rows={4} /> : <input value={String(field.key === "ctaLabel" ? ctaValue.label ?? content[field.key] ?? "" : field.key === "ctaHref" ? ctaValue.href ?? content[field.key] ?? "" : content[field.key] ?? "")} onChange={(event) => update(field.key, event.target.value)} />}</label>)}
    {type === "hero" && <div className="admin-form-columns"><label>Motion preset<select value={String(content.motionPreset ?? "standard")} onChange={(event) => update("motionPreset", event.target.value)}><option value="subtle">Subtle</option><option value="standard">Standard</option><option value="expressive">Expressive</option></select></label><label>Motion intensity<select value={String(content.motionIntensity ?? "medium")} onChange={(event) => update("motionIntensity", event.target.value)}><option value="low">Low</option><option value="medium">Medium</option><option value="high">High</option></select></label></div>}
    {type === "positioning" && <label>Theme preset<select value={String(content.theme ?? "LIGHT")} onChange={(event) => update("theme", event.target.value)}><option value="LIGHT">Light</option><option value="DARK">Dark</option><option value="BRAND">Brand</option></select></label>}
    {type === "faq" && <label>Display mode<select value={String(content.displayMode ?? "ALL_ENABLED")} onChange={(event) => update("displayMode", event.target.value)}><option value="ALL_ENABLED">All enabled</option><option value="SELECTED">Selected FAQ items</option></select></label>}
    {type === "textMedia" && <label>Layout preset<select value={String(content.preset ?? "editorial")} onChange={(event) => update("preset", event.target.value)}><option value="media-left">Media left</option><option value="media-right">Media right</option><option value="full-bleed">Full bleed</option><option value="editorial">Editorial</option></select></label>}
    {(mediaFields[type] ?? []).map((field) => { const selected = content[field.key]; return field.slots ? <div key={field.key} className="admin-picker-slots"><span>{field.label}</span>{Array.from({ length: field.slots }, (_, index) => { const values = Array.isArray(selected) ? selected as string[] : []; return <MediaPicker key={`${field.key}-${index}`} name={`${field.key}-${index}`} label={`${field.label} ${index + 1}`} accept={field.accept} items={media} selectedId={values[index]} onChange={(id) => { const next = [...values]; next[index] = id; update(field.key, next.filter(Boolean)); }} />; })}</div> : <MediaPicker key={field.key} name={field.key} label={field.label} accept={field.accept} items={media} selectedId={typeof selected === "string" ? selected : ""} onChange={(id) => update(field.key, id || undefined)} />; })}
    {(type === "capabilities" || type === "selectedWork" || type === "faq") && <div className="admin-choice-list"><span>{type === "selectedWork" ? "Selected project order" : type === "faq" ? "FAQ selection" : "Linked services"}</span>{choices.map((choice) => <label className="admin-check" key={choice.id}><input type="checkbox" checked={selectedChoices.includes(choice.id)} onChange={() => toggleChoice(choice.id)} /> <span>{choice.label}{choice.detail ? ` — ${choice.detail}` : ""}</span></label>)}</div>}
    {(type === "capabilities" || type === "productionWorkflow" || type === "whyPicVisual") && <ItemList name={type === "productionWorkflow" ? "steps" : "items"} value={content[type === "productionWorkflow" ? "steps" : "items"]} onChange={(value) => update(type === "productionWorkflow" ? "steps" : "items", value)} />}
    <input type="hidden" name="enabled" value="false" /><label className="admin-check"><input name="enabled" type="checkbox" value="true" defaultChecked={section.enabled} /> Show section</label><SubmitButton /></form>;
}
