"use client";

import Link from "next/link";
import { useState } from "react";
import { HeroScene, type HeroContent } from "./HeroScene";
import { services as fallbackServices, type Service } from "@/content/services";
import { projects as fallbackProjects, type Project } from "@/content/work";
import { faqs as fallbackFaqs } from "@/content/faq";
import { MediaVideo } from "@/components/ui/MediaVideo";
import { CmsImage } from "@/components/ui/CmsImage";
import { BeforeAfter } from "@/components/work/BeforeAfter";
import { ProjectArtwork } from "@/components/ui/ProjectArtwork";
import { ImmersiveScenes } from "./ImmersiveScenes";
import { getPublicQuietSectionTypes } from "@/cms/homepage-ordering";

type HomeSection = { type: string; content: unknown; order?: number };
type PublicMedia = { publicUrl: string; alt?: string | null; mediaType?: string; focalX: number | null; focalY: number | null };
function section<T>(sections: HomeSection[] | undefined, type: string): T | undefined { const candidate = sections?.find((item) => item.type === type)?.content; return candidate && typeof candidate === "object" ? candidate as T : undefined; }
export function HomePage({ content }: { content?: { services: Service[]; projects: Project[]; faqs: [string, string][]; page?: { sections: HomeSection[] }; media?: Record<string, PublicMedia> } }) {
  const [activeService, setActiveService] = useState(0);
  const [openFaq, setOpenFaq] = useState<number | null>(null);
  const capabilities = section<{ heading?: string; description?: string; serviceIds?: string[] }>(content?.page?.sections, "capabilities"); const availableServices = content?.services ?? fallbackServices; const services = capabilities?.serviceIds?.length ? capabilities.serviceIds.flatMap((id) => availableServices.filter((service) => service.id === id)) : availableServices; const allProjects = content?.projects ?? fallbackProjects; const faqs = content?.faqs ?? fallbackFaqs; const hero = section<HeroContent>(content?.page?.sections, "hero"); const positioning = section<{ headline?: string; body?: string }>(content?.page?.sections, "positioning"); const beforeAfter = section<{ heading?: string; description?: string; beforeLabel?: string; afterLabel?: string; beforeMediaId?: string; afterMediaId?: string }>(content?.page?.sections, "beforeAfter"); const selectedWork = section<{ heading?: string; description?: string; projectIds?: string[] }>(content?.page?.sections, "selectedWork"); const workflow = section<{ heading?: string; description?: string; steps?: Array<{ title: string; enabled?: boolean }> }>(content?.page?.sections, "productionWorkflow"); const why = section<{ heading?: string; description?: string; items?: Array<{ title: string; description: string; enabled?: boolean }> }>(content?.page?.sections, "whyPicVisual"); const cta = section<{ eyebrow?: string; heading?: string; body?: string; cta?: { label: string; href: string } }>(content?.page?.sections, "cta"); const projects = selectedWork?.projectIds?.length ? selectedWork.projectIds.map((id) => allProjects.find((project) => (project as Project & { id?: string }).id === id)).filter((project): project is Project => Boolean(project)) : allProjects.filter((project) => project.featured !== false); const media = content?.media ?? {}; const image = (id?: string) => id ? media[id] : undefined; const isVisible = (type: string) => !content?.page || content.page.sections.some((item) => item.type === type); const quietSectionTypes = getPublicQuietSectionTypes(content?.page?.sections?.map((item, index) => ({ type: item.type, order: item.order ?? index })));
  return <>
    <HeroScene content={hero} media={media} />
    <section className="editorial"><span className="section-number">01 — INTRODUCTION</span><div className="editorial-statement"><h2>{positioning?.headline ?? <>Your production partner<br /><em>after the shoot.</em></>}</h2><p>{positioning?.body ?? "From high-volume e-commerce catalogs to campaign imagery and short-form motion, PicVisual gives brands one post-production partner for visual consistency across every channel."}</p></div><div className="editorial-rule" /></section>
    {isVisible("capabilities") && services.length > 0 && <section className="capabilities"><div className="section-heading"><span className="section-number">02 — CAPABILITIES</span><h2>{capabilities?.heading ?? <>Every frame<br />has a finish.</>}</h2><p>{capabilities?.description ?? "One coordinated production system for the still and moving image."}</p></div><div className="capability-list">{services.map((service, index) => <article key={service.title} className={`capability ${activeService === index ? "active" : ""}`} onMouseEnter={() => setActiveService(index)}><span className="service-index">{service.index}</span><button onClick={() => setActiveService(index)} aria-expanded={activeService === index}><span>{service.shortTitle}</span><i>↗</i></button><div className="capability-detail"><p>{service.description}</p><ul>{service.items.map((item) => <li key={item}>{item}</li>)}</ul><div className={`capability-swatch swatch-${index}`}><span>{service.index} / PV</span>{service.hero ? <CmsImage asset={service.hero} /> : <div />}</div></div></article>)}</div></section>}
    {isVisible("beforeAfter") && <section className="refined">
      <div className="refined-copy"><span className="section-number">03 — TRANSFORMATION</span><h2>{beforeAfter?.heading ?? <>Raw in.<br /><em>Refined out.</em></>}</h2><p>{beforeAfter?.description ?? "Precision lives in the invisible decisions: tone, texture, edge, light and the consistency that makes a visual system feel whole."}</p></div>
      {image(beforeAfter?.beforeMediaId) && image(beforeAfter?.afterMediaId) ? <BeforeAfter before={{ ...image(beforeAfter?.beforeMediaId)!, alt: image(beforeAfter?.beforeMediaId)?.alt ?? "Before post-production" }} after={{ ...image(beforeAfter?.afterMediaId)!, alt: image(beforeAfter?.afterMediaId)?.alt ?? "After post-production" }} /> : <div className="craft-statement"><span>TONE · TEXTURE · EDGE · LIGHT</span><p>A considered finish.<br />A consistent visual standard.</p></div>}
    </section>}
    <ImmersiveScenes projects={projects} sections={content?.page?.sections} media={media} />
    {isVisible("selectedWork") && projects.length > 0 && <section className="work-section"><div className="work-header"><div><span className="section-number">04 — SELECTED WORK</span><h2>{selectedWork?.heading ?? <>Selected<br />Work</>}</h2></div><p>{selectedWork?.description ?? "A closer look at how raw visual assets become brand-ready content."}</p><Link className="text-link dark" href="/work">All work <i>↗</i></Link></div><div className="work-grid">{projects.map((project, index) => <Link className={`work-item work-${index + 1}`} href={`/work/${project.slug}`} key={project.slug}><ProjectArtwork project={project} /><div className="work-info"><div><span>{project.category}</span><h3>{project.title}</h3></div><span>{project.scope} <i>↗</i></span></div></Link>)}</div></section>}
    {isVisible("motionShowcase") && <section className="motion-showcase"><div className="motion-title"><span className="section-number">05 — MOTION</span><h2>{section<{ heading?: string }>(content?.page?.sections, "motionShowcase")?.heading ?? <>Still has<br /><em>momentum.</em></>}</h2></div><div className="motion-frame">{(() => { const id = section<{ mediaId?: string }>(content?.page?.sections, "motionShowcase")?.mediaId; return id && media[id] ? media[id].mediaType === "VIDEO" ? <MediaVideo src={media[id].publicUrl} label="Motion work" /> : <CmsImage asset={{ ...media[id], alt: media[id].alt ?? "Motion work" }} /> : null; })()}<div className="motion-ring" /><div className="motion-core" /><div className="motion-timeline"><span>00:00</span><b /><i /><i /><i /><span>00:24</span></div><small>MOTION POST / COLOUR / EDIT</small></div><p>Motion work carries the same visual standard into every cut, transition and final export.</p></section>}
    {quietSectionTypes.map((type, sectionIndex) => {
      const current = content?.page?.sections.filter((entry) => quietSectionTypes.includes(entry.type)).sort((a, b) => (a.order ?? 0) - (b.order ?? 0))[sectionIndex];
      const details = (current?.content ?? {}) as Record<string, unknown>;
      const key = `${type}-${sectionIndex}`;
      const currentWorkflow = type === "productionWorkflow" && current ? details as typeof workflow : workflow;
      const currentWhy = type === "whyPicVisual" && current ? details as typeof why : why;
      if (type === "productionWorkflow") return <section className="system" key={key}><div className="system-copy"><span className="section-number">06 — PRODUCTION SYSTEM</span><h2>{currentWorkflow?.heading ?? <>Built for visual production<br /><em>at scale.</em></>}</h2><p>{currentWorkflow?.description ?? "Organized around your briefs, brand standards and approvals—so every asset arrives ready for its next role."}</p></div><div className="flow" aria-label="Production workflow">{(currentWorkflow?.steps?.filter((step) => step.enabled !== false).length ? currentWorkflow.steps.filter((step) => step.enabled !== false) : [{ title: "Send" }, { title: "Prep" }, { title: "Finish" }, { title: "Quality check" }, { title: "Deliver" }]).map((step, index) => <div key={`${step.title}-${index}`}><b>{String(index + 1).padStart(2, "0")}</b><span>{step.title}</span></div>)}</div></section>;
      if (type === "whyPicVisual") return <section className="reasons" key={key}><span className="section-number">07 — WHY PICVISUAL</span><h2>{currentWhy?.heading ?? <>Built for teams<br />that ship content <em>every day.</em></>}</h2>{currentWhy?.description && <p>{currentWhy.description}</p>}<div className="reason-grid">{(currentWhy?.items?.filter((item) => item.enabled !== false).length ? currentWhy.items.filter((item) => item.enabled !== false).map((item) => [item.title, item.description] as const) : [["Pixel-level craft", "Detailed finishing where quality matters."], ["Visual consistency", "Assets aligned to a common brand standard."], ["Built for volume", "A production structure for repeatable content workflows."], ["One visual partner", "Still, motion and creative finishing in one coordinated workflow."]]).map(([title, text], index) => <article key={title}><span>0{index + 1}</span><h3>{title}</h3><p>{text}</p></article>)}</div></section>;
      if (type === "faq" && faqs.length) return <section className="faq" key={key}><div><span className="section-number">08 — FAQ</span><h2>{section<{ heading?: string }>(content?.page?.sections, "faq")?.heading ?? <>Good work<br />starts clear.</>}</h2></div><div className="faq-list">{faqs.map(([question, answer], index) => <div className={`faq-item ${openFaq === index ? "open" : ""}`} key={question}><button onClick={() => setOpenFaq(openFaq === index ? null : index)} aria-expanded={openFaq === index} aria-controls={`faq-answer-${index}`}><span>{question}</span><i>+</i></button><div className="faq-answer" id={`faq-answer-${index}`} aria-hidden={openFaq !== index}><p>{answer}</p></div></div>)}</div></section>;
      if (["textMedia", "richText"].includes(type) && (details.heading || details.body)) return <section className={`home-editorial-block ${String(details.preset ?? "editorial")}`} key={key}><div>{typeof details.heading === "string" && <h2>{details.heading}</h2>}{typeof details.body === "string" && details.body.split("\n\n").map((paragraph) => <p key={paragraph}>{paragraph}</p>)}</div>{typeof details.mediaId === "string" && media[details.mediaId] && <CmsImage asset={{ ...media[details.mediaId], alt: media[details.mediaId].alt ?? "" }} />}</section>;
      if (type === "gallery" && Array.isArray(details.mediaIds) && details.mediaIds.length) return <section className="home-gallery" key={key}>{details.mediaIds.map((id) => typeof id === "string" && media[id] ? <CmsImage key={id} asset={{ ...media[id], alt: media[id].alt ?? "" }} /> : null)}</section>;
      if (type === "video" && typeof details.mediaId === "string" && media[details.mediaId]) return <section className="home-video" key={key}><video src={media[details.mediaId].publicUrl} poster={typeof details.posterMediaId === "string" ? media[details.posterMediaId]?.publicUrl : undefined} controls playsInline preload="none" /></section>;
      return null;
    })}
    <section className="project-cta"><span className="eyebrow">{cta?.eyebrow ?? "START A CONVERSATION"}</span><h2>{cta?.heading ?? <>Have content<br />in production?</>}</h2><p>{cta?.body ?? "Let's make it ready for market."}</p><div><Link className="button button-light" href={cta?.cta?.href ?? "/contact"}>{cta?.cta?.label ?? "Start a Project"} <i>↗</i></Link><Link className="text-link" href="/work">View Selected Work <i>↗</i></Link></div><span className="cta-mark">PV</span></section>
  </>;
}
