"use client";
/* eslint-disable @next/next/no-img-element -- CMS media providers use runtime URLs. */

import { useEffect, useMemo, useRef } from "react";
import Link from "next/link";
import gsap from "gsap";
import { ScrollTrigger } from "gsap/ScrollTrigger";
import { useGSAP } from "@gsap/react";
import type { Project } from "@/content/work";
import { ProjectArtwork } from "@/components/ui/ProjectArtwork";

gsap.registerPlugin(ScrollTrigger, useGSAP);
const copy = { image: ["IMAGE POST", "Pixel-level craft, frame by frame."], video: ["VIDEO EDIT", "Colour, rhythm, and the decisive cut."], motion: ["MOTION", "Still imagery with a pulse."], product: ["PRODUCT", "From source to a clean product page."], jewelry: ["JEWELRY", "Light held at its sharpest edge."], creative: ["CREATIVE", "Independent layers, one finished world."], development: ["INTERACTIVE", "Creative development, built to move."] } as const;
type Kind = keyof typeof copy;
type SceneSection = { type: string; content: unknown };
type PublicMedia = { publicUrl: string; focalX: number | null; focalY: number | null };
type SceneData = Record<string, unknown>;

function value(sections: SceneSection[] | undefined, type: string) { const found = sections?.find((section) => section.type === type)?.content; return found && typeof found === "object" ? found as SceneData : {}; }
function mediaStyle(id: unknown, media: Record<string, PublicMedia>) { const asset = typeof id === "string" ? media[id] : undefined; return asset ? { src: asset.publicUrl, style: { objectPosition: `${asset.focalX ?? 50}% ${asset.focalY ?? 50}%` } } : undefined; }
function ManagedMedia({ id, media, className }: { id: unknown; media: Record<string, PublicMedia>; className?: string }) { const asset = mediaStyle(id, media); return asset ? <img className={className ?? "pv-managed-media"} src={asset.src} alt="" style={asset.style} /> : null; }

function Scene({ kind, content, media }: { kind: Kind; content: SceneData; media: Record<string, PublicMedia> }) {
  const [fallbackLabel, fallbackTitle] = copy[kind]; const label = typeof content.label === "string" ? content.label : fallbackLabel; const title = typeof content.heading === "string" ? content.heading : fallbackTitle; const description = typeof content.description === "string" ? content.description : kind === "image" ? "RAW / FINISHED — move through the image to reveal the refined finish." : kind === "video" ? "Move across the timeline to grade the frame." : kind === "motion" ? "Keyframes bend toward the pointer." : kind === "product" ? "Selection, shadow and background resolve into a final PDP." : kind === "jewelry" ? "Guide the inspection light across the surface." : kind === "creative" ? "Source layers occupy independent depth." : "Interface fragments connect into a single experience.";
  const array = (key: string) => Array.isArray(content[key]) ? content[key] : [];
  return <section className={`pv-scene pv-${kind}`} data-cursor={kind}><div className="pv-safe-copy"><span>{label}</span><h2>{title}</h2><p>{description}</p></div>
    {kind === "image" && <div className="pv-retouch-stage"><div className="pv-raw"><ManagedMedia id={content.rawMediaId} media={media} /><b>RAW</b></div><div className="pv-finished"><ManagedMedia id={content.finishedMediaId} media={media} /><b>FINISHED</b></div><i className="pv-retouch-edge" /><div className="pv-detail-window one"><ManagedMedia id={array("detailMediaIds")[0]} media={media} /></div><div className="pv-detail-window two"><ManagedMedia id={array("detailMediaIds")[1]} media={media} /></div></div>}
    {kind === "video" && <div className="pv-video-stage"><div className="pv-cinema"><ManagedMedia id={content.posterMediaId} media={media} /><video className="pv-managed-video" src={mediaStyle(content.videoMediaId, media)?.src} muted playsInline preload="metadata" /><span>RAW FRAME / 01</span><i /></div><div className="pv-timeline">{[0, 1, 2].map((index) => <i key={index}><ManagedMedia id={array("timelineMediaIds")[index]} media={media} /></i>)}<em /></div><div className="pv-grade"><span>LOW</span><span>MID</span><span>FINAL</span></div></div>}
    {kind === "motion" && <div className="pv-motion-stage"><svg viewBox="0 0 700 480" aria-hidden="true"><path d="M50 390 C210 40 430 510 650 90" /><path d="M70 180 C250 430 470 30 630 300" /></svg>{["a", "b", "c"].map((slot, index) => <div className={`pv-motion-frame ${slot}`} key={slot}><ManagedMedia id={array("reelMediaIds")[index] ?? array("posterMediaIds")[index]} media={media} /></div>)}<i className="pv-key k1" /><i className="pv-key k2" /><i className="pv-key k3" /></div>}
    {kind === "product" && <div className="pv-product-stage"><div className="pv-product-source"><ManagedMedia id={content.sourceMediaId} media={media} />SOURCE</div><div className="pv-product-shadow"><ManagedMedia id={content.shadowMediaId} media={media} /></div><div className="pv-product-cutout"><ManagedMedia id={content.finalMediaId ?? content.cutoutMediaId} media={media} /><span>FINAL PDP</span></div><i className="pv-select-box" /></div>}
    {kind === "jewelry" && <div className="pv-jewelry-stage"><div className="pv-jewel"><ManagedMedia id={content.primaryMediaId} media={media} /><i /></div><div className="pv-macro"><ManagedMedia id={content.macroMediaId} media={media} /></div><span>MACRO / SURFACE</span></div>}
    {kind === "creative" && <div className="pv-creative-stage"><i className="pv-layer back"><ManagedMedia id={content.backgroundMediaId} media={media} />BACKGROUND</i><i className="pv-layer shadow"><ManagedMedia id={content.shadowMediaId} media={media} />SHADOW</i><i className="pv-layer subject"><ManagedMedia id={content.subjectMediaId ?? content.finalMediaId} media={media} />SUBJECT</i><i className="pv-layer light"><ManagedMedia id={content.lightMediaId} media={media} />LIGHT</i><i className="pv-layer texture"><ManagedMedia id={content.textureMediaId} media={media} />TEXTURE</i></div>}
    {kind === "development" && <div className="pv-dev-stage"><div className="pv-browser"><ManagedMedia id={content.interfaceMediaId} media={media} /><b /><i /><i /><i /><em /></div><ManagedMedia className="pv-dev-fragment" id={content.fragmentMediaId ?? content.screenshotMediaId} media={media} /><svg viewBox="0 0 700 450" aria-hidden="true"><path d="M86 114 L320 220 L600 80" /><path d="M90 345 L320 220 L604 364" /></svg><i className="pv-node n1" /><i className="pv-node n2" /><i className="pv-node n3" /><i className="pv-node n4" /></div>}
  </section>;
}

export function ImmersiveScenes({ projects, sections, media = {} }: { projects: Project[]; sections?: SceneSection[]; media?: Record<string, PublicMedia> }) {
  const root = useRef<HTMLDivElement>(null); const cursor = useRef<HTMLDivElement>(null); const workWorld = useRef<HTMLDivElement>(null); const activeTitle = useRef<HTMLHeadingElement>(null);
  const scenes = useMemo(() => ({ image: value(sections, "imagePost"), video: value(sections, "videoEdit"), motion: value(sections, "motion"), product: value(sections, "product"), jewelry: value(sections, "jewelry"), creative: value(sections, "creative"), development: value(sections, "development") }), [sections]);
  useEffect(() => { if (!window.matchMedia("(pointer:fine)").matches) return; const cursorEl = cursor.current; const rootEl = root.current; if (!cursorEl || !rootEl) return; rootEl.classList.add("pv-pointer-ready"); const x = gsap.quickTo(cursorEl, "x", { duration: .14, ease: "power3.out" }); const y = gsap.quickTo(cursorEl, "y", { duration: .14, ease: "power3.out" }); const onMove = (event: PointerEvent) => { x(event.clientX); y(event.clientY); const scene = (event.target as Element).closest<HTMLElement>("[data-cursor]"); cursorEl.dataset.mode = scene?.dataset.cursor ?? "default"; if (!scene) return; const rect = scene.getBoundingClientRect(); const px = Math.max(0, Math.min(100, (event.clientX - rect.left) / rect.width * 100)); const py = Math.max(0, Math.min(100, (event.clientY - rect.top) / rect.height * 100)); scene.style.setProperty("--px", `${px}%`); scene.style.setProperty("--py", `${py}%`); if (scene.dataset.cursor === "work") { workWorld.current?.style.setProperty("--camera-x", `${(px - 50) * .17}px`); workWorld.current?.style.setProperty("--camera-y", `${(py - 50) * .11}px`); } }; window.addEventListener("pointermove", onMove, { passive: true }); return () => { rootEl.classList.remove("pv-pointer-ready"); window.removeEventListener("pointermove", onMove); }; }, []);
  useGSAP(() => { if (window.matchMedia("(prefers-reduced-motion:reduce)").matches) return; const ctx = gsap.context(() => { const stages: Array<[string, gsap.TweenVars]> = [[".pv-retouch-stage", { scale: 1.08, rotateY: 6 }], [".pv-video-stage", { scale: 1.06, rotateX: 3 }], [".pv-motion-stage", { rotateZ: 3 }], [".pv-product-stage", { scale: 1.07 }], [".pv-jewelry-stage", { scale: 1.09 }], [".pv-creative-stage", { rotateY: -6 }], [".pv-dev-stage", { scale: 1.05 }]]; stages.forEach(([selector, vars]) => gsap.to(selector, { ...vars, scrollTrigger: { trigger: selector, start: "top bottom", end: "bottom top", scrub: .7 } })); gsap.utils.toArray<HTMLElement>(".pv-scene").forEach((scene) => gsap.to(scene.querySelector(".pv-safe-copy"), { yPercent: -18, opacity: 0, ease: "none", scrollTrigger: { trigger: scene, start: "bottom 40%", end: "bottom 7%", scrub: .22 } }));
    const work = gsap.timeline({ scrollTrigger: { trigger: ".pv-work-field", start: "top top", end: "+=3000", scrub: .8, pin: true, anticipatePin: 1, onUpdate: (self) => { const index = self.progress < .42 ? 0 : self.progress < .76 ? 1 : Math.min(projects.length - 1, 2); if (activeTitle.current && projects[index]) activeTitle.current.textContent = projects[index].title; } } });
    work.set(".pv-plane-0", { z: 180, xPercent: -18, yPercent: 8, rotateY: 12, scale: .8 }).set(".pv-plane-1", { z: -720, xPercent: 5, yPercent: -14, rotateY: -8, scale: .48 }).set(".pv-plane-2", { z: -150, xPercent: 34, yPercent: 18, rotateY: -16, scale: .65 }).set(".pv-plane-3", { z: -980, xPercent: -36, yPercent: -30, rotateY: 18, scale: .4 }).to(".pv-plane-0", { z: 1250, xPercent: -165, yPercent: -8, rotateY: 24, scale: 2.25, opacity: .08, duration: .32 }, .14).to(".pv-plane-1", { z: 550, xPercent: -4, yPercent: 2, rotateY: -4, scale: 1.18, opacity: 1, duration: .25 }, .37).to(".pv-plane-1", { z: 1330, xPercent: 112, yPercent: -12, rotateY: -22, scale: 2.3, opacity: .08, duration: .23 }, .58).to(".pv-plane-2", { z: 780, xPercent: -10, yPercent: 6, rotateY: 5, scale: 1.4, opacity: 1, duration: .28 }, .69).to(".pv-plane-3", { z: 180, xPercent: 20, yPercent: -4, rotateY: -4, scale: .83, opacity: .9, duration: .24 }, .82); }, root); return () => ctx.revert(); }, { scope: root, dependencies: [projects] });
  return <div ref={root} className="pv-immersive"><div ref={cursor} className="pv-cursor" aria-hidden="true"><svg viewBox="0 0 32 32"><path className="pv-icon-image" d="M16 3 26 27 16 22 6 27Z M26 27l3 3" /><circle className="pv-icon-video" cx="16" cy="16" r="10" /><path className="pv-icon-video" d="M16 3v5M16 24v5M3 16h5M24 16h5" /><path className="pv-icon-motion" d="m16 4 10 12-10 12L6 16Z" /><path className="pv-icon-product" d="M4 12V4h8M20 4h8v8M28 20v8h-8M12 28H4v-8" /><path className="pv-icon-jewelry" d="M16 3v7M16 22v7M3 16h7M22 16h7" /><path className="pv-icon-creative" d="m5 4 20 12-10 2-5 10Z" /><path className="pv-icon-development" d="M10 4v24M10 4h8M10 28h8M23 20l5 5-5 5" /><path className="pv-icon-work" d="M4 12V4h8M20 4h8M20 4h8v8M28 20v8h-8M12 28H4v-8" /></svg></div>{(Object.keys(copy) as Kind[]).map((kind) => <Scene key={kind} kind={kind} content={scenes[kind]} media={media} />)}<section className="pv-work-field" data-cursor="work"><header><span>SELECTED WORK</span><h2 ref={activeTitle}>{projects[0]?.title ?? "Finished worlds."}</h2><p>Scroll through the camera field</p></header><div ref={workWorld} className="pv-work-depth">{projects.slice(0, 5).map((project, index) => <div className={`pv-work-plane pv-plane-${index % 4}`} key={project.slug}><ProjectArtwork project={project} /></div>)}</div><div className="pv-work-actions"><Link href={projects[0] ? `/work/${projects[0].slug}` : "/work"}>View project ↗</Link><Link href="/work">View all work ↗</Link></div></section></div>;
}
