"use client";

import { useEffect, useMemo, useRef, useState } from "react";
import Link from "next/link";
import gsap from "gsap";
import { ScrollTrigger } from "gsap/ScrollTrigger";
import { useGSAP } from "@gsap/react";
import type { Project } from "@/content/work";
import { MediaVideo } from "@/components/ui/MediaVideo";
import { CmsImage } from "@/components/ui/CmsImage";
import { ProjectArtwork } from "@/components/ui/ProjectArtwork";

gsap.registerPlugin(ScrollTrigger, useGSAP);
const copy = { image: ["IMAGE POST", "Pixel-level craft, frame by frame."], video: ["VIDEO EDIT", "Colour, rhythm, and the decisive cut."], motion: ["MOTION", "Still imagery with a pulse."], product: ["PRODUCT", "From source to a clean product page."], jewelry: ["JEWELRY", "Light held at its sharpest edge."], creative: ["CREATIVE", "Independent layers, one finished world."], development: ["INTERACTIVE", "Creative development, built to move."] } as const;
type Kind = keyof typeof copy;
type SceneSection = { type: string; content: unknown };
type PublicMedia = { publicUrl: string; alt?: string | null; mediaType?: string; focalX: number | null; focalY: number | null; width?: number | null; height?: number | null };
type SceneData = Record<string, unknown>;

function value(sections: SceneSection[] | undefined, type: string) { const found = sections?.find((section) => section.type === type)?.content; return found && typeof found === "object" ? found as SceneData : {}; }
function mediaStyle(id: unknown, media: Record<string, PublicMedia>) { const asset = typeof id === "string" ? media[id] : undefined; return asset ? { src: asset.publicUrl, style: { objectPosition: `${asset.focalX ?? 50}% ${asset.focalY ?? 50}%` } } : undefined; }
function ManagedMedia({ id, media, className }: { id: unknown; media: Record<string, PublicMedia>; className?: string }) { const asset = typeof id === "string" ? media[id] : undefined; if (!asset) return null; return asset.mediaType === "VIDEO" ? <MediaVideo className={className ?? "pv-managed-media"} src={asset.publicUrl} label={asset.alt || "Motion preview"} /> : <CmsImage className={className ?? "pv-managed-media"} asset={{ ...asset, alt: asset.alt ?? "" }} sizes="(max-width: 768px) 100vw, 65vw" />; }

function Scene({ kind, content, media }: { kind: Kind; content: SceneData; media: Record<string, PublicMedia> }) {
  const [fallbackLabel, fallbackTitle] = copy[kind]; const label = typeof content.label === "string" ? content.label : fallbackLabel; const title = typeof content.heading === "string" ? content.heading : fallbackTitle; const description = typeof content.description === "string" ? content.description : kind === "image" ? "RAW / FINISHED — move through the image to reveal the refined finish." : kind === "video" ? "Move across the timeline to grade the frame." : kind === "motion" ? "Keyframes bend toward the pointer." : kind === "product" ? "Selection, shadow and background resolve into a final PDP." : kind === "jewelry" ? "Guide the inspection light across the surface." : kind === "creative" ? "Source layers occupy independent depth." : "Interface fragments connect into a single experience.";
  const array = (key: string) => Array.isArray(content[key]) ? content[key] : [];
  return <section className={`pv-scene pv-${kind}`} data-cursor={kind}><div className="pv-safe-copy"><span>{label}</span><h2>{title}</h2><p>{description}</p></div>
    {kind === "image" && <div className="pv-retouch-stage" data-comparison={!!content.rawMediaId && !!content.finishedMediaId}><div className="pv-raw"><ManagedMedia id={content.rawMediaId} media={media} /><b>{content.rawMediaId ? "RAW" : "CRAFT"}</b></div><div className="pv-finished"><ManagedMedia id={content.finishedMediaId ?? content.primaryMediaId} media={media} /><b>FINISHED</b></div><i className="pv-retouch-edge" /><div className="pv-detail-window one"><ManagedMedia id={array("detailMediaIds")[0]} media={media} /></div><div className="pv-detail-window two"><ManagedMedia id={array("detailMediaIds")[1]} media={media} /></div></div>}
    {kind === "video" && <div className="pv-video-stage"><div className="pv-cinema"><ManagedMedia id={content.posterMediaId} media={media} />{mediaStyle(content.videoMediaId, media) && <MediaVideo className="pv-managed-video" src={mediaStyle(content.videoMediaId, media)!.src} poster={mediaStyle(content.posterMediaId, media)?.src} label="Video post-production" />}<span>RAW FRAME / 01</span><i /></div><div className="pv-timeline">{[0, 1, 2].map((index) => <i key={index}><ManagedMedia id={array("timelineMediaIds")[index]} media={media} /></i>)}<em /></div><div className="pv-grade"><span>LOW</span><span>MID</span><span>FINAL</span></div></div>}
    {kind === "motion" && <div className="pv-motion-stage"><svg viewBox="0 0 700 480" aria-hidden="true"><path d="M50 390 C210 40 430 510 650 90" /><path d="M70 180 C250 430 470 30 630 300" /></svg>{["a", "b", "c"].map((slot, index) => <div className={`pv-motion-frame ${slot}`} key={slot}><ManagedMedia id={array("reelMediaIds")[index] ?? array("posterMediaIds")[index]} media={media} /></div>)}<i className="pv-key k1" /><i className="pv-key k2" /><i className="pv-key k3" /></div>}
    {kind === "product" && <div className="pv-product-stage" data-final-only={!content.sourceMediaId && !!content.finalMediaId}><div className="pv-product-source"><ManagedMedia id={content.sourceMediaId} media={media} />SOURCE</div><div className="pv-product-shadow"><ManagedMedia id={content.shadowMediaId} media={media} /></div><div className="pv-product-cutout"><ManagedMedia id={content.finalMediaId ?? content.cutoutMediaId ?? content.primaryMediaId} media={media} /><span>FINAL PDP</span></div><i className="pv-select-box" /></div>}
    {kind === "jewelry" && <div className="pv-jewelry-stage"><div className="pv-jewel"><ManagedMedia id={content.primaryMediaId} media={media} /><i /></div><div className="pv-macro"><ManagedMedia id={content.macroMediaId} media={media} /></div><span>MACRO / SURFACE</span></div>}
    {kind === "creative" && <div className="pv-creative-stage"><i className="pv-layer back"><ManagedMedia id={content.backgroundMediaId} media={media} />BACKGROUND</i><i className="pv-layer shadow"><ManagedMedia id={content.shadowMediaId} media={media} />SHADOW</i><i className="pv-layer subject"><ManagedMedia id={content.subjectMediaId ?? content.finalMediaId} media={media} />SUBJECT</i><i className="pv-layer light"><ManagedMedia id={content.lightMediaId} media={media} />LIGHT</i><i className="pv-layer texture"><ManagedMedia id={content.textureMediaId} media={media} />TEXTURE</i></div>}
    {kind === "development" && <div className="pv-dev-stage"><div className="pv-browser"><ManagedMedia id={content.interfaceMediaId} media={media} /><b /><i /><i /><i /><em /></div><ManagedMedia className="pv-dev-fragment" id={content.fragmentMediaId ?? content.screenshotMediaId} media={media} /><svg viewBox="0 0 700 450" aria-hidden="true"><path d="M86 114 L320 220 L600 80" /><path d="M90 345 L320 220 L604 364" /></svg><i className="pv-node n1" /><i className="pv-node n2" /><i className="pv-node n3" /><i className="pv-node n4" /></div>}
    {!!(content.mobileMediaId || content.mobileVideoMediaId) && <div className="pv-mobile-asset"><ManagedMedia id={content.mobileVideoMediaId ?? content.mobileMediaId} media={media} /></div>}
  </section>;
}

export function ImmersiveScenes({ projects, sections, media = {} }: { projects: Project[]; sections?: SceneSection[]; media?: Record<string, PublicMedia> }) {
  const root = useRef<HTMLDivElement>(null); const cursor = useRef<HTMLDivElement>(null); const workWorld = useRef<HTMLDivElement>(null); const activeTitle = useRef<HTMLHeadingElement>(null); const [activeProject, setActiveProject] = useState(0);
  const planes = useMemo(() => projects.length === 1 && projects[0].gallery?.length ? projects[0].gallery.filter((asset) => asset.mediaType === "IMAGE").slice(0, 4).map((asset) => ({ ...projects[0], thumbnail: asset })) : projects.slice(0, 8), [projects]);
  const workVisible = !sections || sections.some((section) => section.type === "selectedWork");
  const scenes = useMemo(() => ({ image: value(sections, "imagePost"), video: value(sections, "videoEdit"), motion: value(sections, "motion"), product: value(sections, "product"), jewelry: value(sections, "jewelry"), creative: value(sections, "creative"), development: value(sections, "development") }), [sections]);
  useEffect(() => { if (!window.matchMedia("(pointer:fine)").matches) return; const cursorEl = cursor.current; const rootEl = root.current; if (!cursorEl || !rootEl) return; rootEl.classList.add("pv-pointer-ready"); const x = gsap.quickTo(cursorEl, "x", { duration: .14, ease: "power3.out" }); const y = gsap.quickTo(cursorEl, "y", { duration: .14, ease: "power3.out" }); const onMove = (event: PointerEvent) => { x(event.clientX); y(event.clientY); const scene = (event.target as Element).closest<HTMLElement>("[data-cursor]"); cursorEl.dataset.mode = scene?.dataset.cursor ?? "default"; if (!scene) return; const rect = scene.getBoundingClientRect(); const px = Math.max(0, Math.min(100, (event.clientX - rect.left) / rect.width * 100)); const py = Math.max(0, Math.min(100, (event.clientY - rect.top) / rect.height * 100)); scene.style.setProperty("--px", `${px}%`); scene.style.setProperty("--py", `${py}%`); if (scene.dataset.cursor === "work") { workWorld.current?.style.setProperty("--camera-x", `${(px - 50) * .17}px`); workWorld.current?.style.setProperty("--camera-y", `${(py - 50) * .11}px`); } }; window.addEventListener("pointermove", onMove, { passive: true }); return () => { rootEl.classList.remove("pv-pointer-ready"); window.removeEventListener("pointermove", onMove); }; }, []);
  useGSAP(() => { if (window.matchMedia("(prefers-reduced-motion:reduce), (max-width: 768px), (pointer:coarse)").matches) return; const ctx = gsap.context(() => { const stages: Array<[string, gsap.TweenVars]> = [[".pv-retouch-stage", { scale: 1.08, rotateY: 6 }], [".pv-video-stage", { scale: 1.06, rotateX: 3 }], [".pv-motion-stage", { rotateZ: 3 }], [".pv-product-stage", { scale: 1.07 }], [".pv-jewelry-stage", { scale: 1.09 }], [".pv-creative-stage", { rotateY: -6 }], [".pv-dev-stage", { scale: 1.05 }]]; stages.forEach(([selector, vars]) => gsap.to(selector, { ...vars, scrollTrigger: { trigger: selector, start: "top bottom", end: "bottom top", scrub: .7 } })); gsap.utils.toArray<HTMLElement>(".pv-scene").forEach((scene) => gsap.to(scene.querySelector(".pv-safe-copy"), { yPercent: -18, opacity: 0, ease: "none", scrollTrigger: { trigger: scene, start: "bottom 40%", end: "bottom 7%", scrub: .22 } }));
    if (!workVisible || !planes.length) return;
    const total = planes.length;
    const work = gsap.timeline({ scrollTrigger: { trigger: ".pv-work-field", start: "top top", end: `+=${Math.max(1000, total * 650)}`, scrub: .7, pin: true, anticipatePin: 1, onUpdate: (self) => { setActiveProject(Math.min(total - 1, Math.floor(self.progress * total))); } } });
    planes.forEach((_, index) => {
      const selector = `.pv-plane-${index}`;
      work.set(selector, { z: -index * 420, xPercent: index % 2 ? 24 : -18, yPercent: index % 2 ? -10 : 8, rotateY: index % 2 ? -8 : 10, scale: index === 0 ? .9 : .6, opacity: index === 0 ? 1 : .65 }, 0);
      work.to(selector, { z: 260, xPercent: 0, yPercent: 0, rotateY: 0, scale: 1, opacity: 1, duration: .65 }, index);
      if (index < total - 1) work.to(selector, { z: 1300, xPercent: index % 2 ? 140 : -140, rotateY: index % 2 ? -22 : 22, scale: 1.8, opacity: 0, duration: .5 }, index + .65);
    });
 }, root); return () => ctx.revert(); }, { scope: root, dependencies: [planes, workVisible] });
  return <div ref={root} className="pv-immersive"><div ref={cursor} className="pv-cursor" data-mode="default" aria-hidden="true"><svg viewBox="0 0 32 32"><path className="pv-icon-image" d="M16 3 26 27 16 22 6 27Z M26 27l3 3" /><circle className="pv-icon-video" cx="16" cy="16" r="10" /><path className="pv-icon-video" d="M16 3v5M16 24v5M3 16h5M24 16h5" /><path className="pv-icon-motion" d="m16 4 10 12-10 12L6 16Z" /><path className="pv-icon-product" d="M4 12V4h8M20 4h8v8M28 20v8h-8M12 28H4v-8" /><path className="pv-icon-jewelry" d="M16 3v7M16 22v7M3 16h7M22 16h7" /><path className="pv-icon-creative" d="m5 4 20 12-10 2-5 10Z" /><path className="pv-icon-development" d="M10 4v24M10 4h8M10 28h8M23 20l5 5-5 5" /><path className="pv-icon-work" d="M4 12V4h8M20 4h8M20 4h8v8M28 20v8h-8M12 28H4v-8" /></svg></div>{(Object.keys(copy) as Kind[]).filter((kind) => !sections || sections.some((section) => section.type === ({ image: "imagePost", video: "videoEdit", motion: "motion", product: "product", jewelry: "jewelry", creative: "creative", development: "development" })[kind])).map((kind) => <Scene key={kind} kind={kind} content={scenes[kind]} media={media} />)}{workVisible && planes.length > 0 && <section className="pv-work-field" data-cursor="work"><header><span>SELECTED WORK</span><h2 ref={activeTitle}>{planes[activeProject]?.title ?? planes[0]?.title}</h2><p>A closer look at the finished work</p></header><div ref={workWorld} className="pv-work-depth">{planes.map((project, index) => <div className={`pv-work-plane pv-plane-${index}`} key={`${project.slug}-${index}`}><ProjectArtwork project={project} /></div>)}</div><div className="pv-work-actions"><Link href={planes[activeProject] ? `/work/${planes[activeProject].slug}` : "/work"}>View project ↗</Link><Link href="/work">View all work ↗</Link></div></section>}</div>;
}
