import type { PublicAsset } from "./work";

export type DemoAsset = PublicAsset & { mediaType: "IMAGE"; sampleLabel: string };

/**
 * Local, non-client presentation media. Public CMS media always takes priority.
 * Keeping these assets in one module makes the fallback simple to replace or remove.
 */
export const demoMedia = {
  hero: {
    publicUrl: "/demo/home/hero-product.jpg",
    alt: "Sample visual of an unbranded blue glass product in a cinematic studio set",
    width: 1672,
    height: 941,
    focalX: 68,
    focalY: 50,
    mediaType: "IMAGE",
    sampleLabel: "Sample visual / product finish",
  },
  beauty: {
    publicUrl: "/demo/home/fashion-beauty.jpg",
    alt: "Sample beauty retouching visual with natural skin texture and blue fabric",
    width: 1122,
    height: 1402,
    focalX: 52,
    focalY: 42,
    mediaType: "IMAGE",
    sampleLabel: "Sample visual / beauty retouching",
  },
  jewelry: {
    publicUrl: "/demo/home/jewelry-macro.jpg",
    alt: "Sample jewelry retouching visual of an unbranded silver ring",
    width: 1122,
    height: 1402,
    focalX: 52,
    focalY: 48,
    mediaType: "IMAGE",
    sampleLabel: "Sample visual / jewelry detail",
  },
  product: {
    publicUrl: "/demo/home/product-ecommerce.jpg",
    alt: "Sample e-commerce product visual of an unbranded shoe",
    width: 1536,
    height: 1024,
    focalX: 58,
    focalY: 48,
    mediaType: "IMAGE",
    sampleLabel: "Sample visual / e-commerce finish",
  },
  creative: {
    publicUrl: "/demo/home/creative-composite.jpg",
    alt: "Sample CGI composite with glass, fabric and sculptural forms",
    width: 1536,
    height: 1024,
    focalX: 54,
    focalY: 50,
    mediaType: "IMAGE",
    sampleLabel: "Sample visual / creative composite",
  },
  motion: {
    publicUrl: "/demo/home/motion-color.jpg",
    alt: "Sample motion and color-grading sequence with a dancer",
    width: 1672,
    height: 941,
    focalX: 50,
    focalY: 50,
    mediaType: "IMAGE",
    sampleLabel: "Sample visual / motion and colour",
  },
  beautyDetail: {
    publicUrl: "/demo/home/beauty-detail-study.jpg",
    alt: "Sample editorial beauty macro showing natural skin texture and controlled tonal detail",
    width: 1536,
    height: 1024,
    focalX: 69,
    focalY: 47,
    mediaType: "IMAGE",
    sampleLabel: "Sample visual / texture study",
  },
  productMaterial: {
    publicUrl: "/demo/home/product-material-study.jpg",
    alt: "Sample unbranded product material study with ceramic and blue acrylic",
    width: 1536,
    height: 1024,
    focalX: 52,
    focalY: 50,
    mediaType: "IMAGE",
    sampleLabel: "Sample visual / material finish",
  },
  creativeMaterial: {
    publicUrl: "/demo/home/creative-material-study.jpg",
    alt: "Sample creative composite of glass, brushed metal and blue fabric",
    width: 1672,
    height: 941,
    focalX: 52,
    focalY: 50,
    mediaType: "IMAGE",
    sampleLabel: "Sample visual / composite study",
  },
  beautyRaw: {
    publicUrl: "/demo/home/beauty-reference-raw.jpg",
    alt: "Sample unretouched beauty reference portrait with natural skin texture",
    width: 1024,
    height: 1536,
    focalX: 50,
    focalY: 36,
    mediaType: "IMAGE",
    sampleLabel: "Sample visual / source portrait",
  },
  productSource: {
    publicUrl: "/demo/home/product-source-studio.jpg",
    alt: "Sample product source capture with an unbranded ceramic vessel and visible studio setup",
    width: 1536,
    height: 1024,
    focalX: 49,
    focalY: 53,
    mediaType: "IMAGE",
    sampleLabel: "Sample visual / source capture",
  },
  gemstone: {
    publicUrl: "/demo/home/jewelry-gemstone-detail.jpg",
    alt: "Sample macro finishing study of an unbranded clear gemstone in silver prongs",
    width: 1536,
    height: 1024,
    focalX: 51,
    focalY: 50,
    mediaType: "IMAGE",
    sampleLabel: "Sample visual / gemstone detail",
  },
  filmFrame: {
    publicUrl: "/demo/home/cinematic-film-frame.jpg",
    alt: "Sample cinematic movement frame with blue fabric in a concrete studio",
    width: 1672,
    height: 941,
    focalX: 48,
    focalY: 46,
    mediaType: "IMAGE",
    sampleLabel: "Sample visual / cinematic frame",
  },
  productPolished: {
    publicUrl: "/demo/home/product-campaign-polished.jpg",
    alt: "Sample polished campaign image of an unbranded cobalt glass cosmetic vessel",
    width: 1536,
    height: 1024,
    focalX: 54,
    focalY: 53,
    mediaType: "IMAGE",
    sampleLabel: "Sample visual / polished campaign",
  },
  motionSequence: {
    publicUrl: "/demo/home/motion-frame-sequence.jpg",
    alt: "Sample four-frame motion study of blue fabric suspended above a charcoal surface",
    width: 2172,
    height: 724,
    focalX: 50,
    focalY: 50,
    mediaType: "IMAGE",
    sampleLabel: "Sample visual / motion sequence",
  },
  compositingLayers: {
    publicUrl: "/demo/home/compositing-layer-study.jpg",
    alt: "Sample compositing material study with curved glass, brushed metal, fabric and plaster",
    width: 1536,
    height: 1024,
    focalX: 50,
    focalY: 52,
    mediaType: "IMAGE",
    sampleLabel: "Sample visual / compositing layers",
  },
  workstation: {
    publicUrl: "/demo/home/production-workstation.jpg",
    alt: "Sample post-production workstation with colour controls and an abstract grading interface",
    width: 1536,
    height: 1024,
    focalX: 54,
    focalY: 48,
    mediaType: "IMAGE",
    sampleLabel: "Sample visual / production workflow",
  },
} satisfies Record<string, DemoAsset>;

export const demoWorlds = [
  {
    type: "imagePost",
    label: "IMAGE POST / FASHION + BEAUTY",
    heading: "Texture, tone, detail.",
    description: "A sample presentation of careful beauty finishing, tonal control and natural detail. Replace it with approved media from the Homepage editor.",
    assets: [demoMedia.beautyDetail, demoMedia.beautyRaw],
  },
  {
    type: "product",
    label: "PRODUCT / E-COMMERCE",
    heading: "Clean enough to inspect.",
    description: "Cutouts, surfaces, shadows and colour consistency composed for high-volume commerce and campaign use.",
    assets: [demoMedia.productPolished, demoMedia.productSource],
  },
  {
    type: "jewelry",
    label: "JEWELRY / MACRO",
    heading: "Precision at every scale.",
    description: "A sample macro study built around controlled metal, clean facets and the small decisions that make detail feel premium.",
    assets: [demoMedia.gemstone, demoMedia.jewelry],
  },
  {
    type: "videoEdit",
    label: "VIDEO / EDIT / COLOUR",
    heading: "Every cut earns its colour.",
    description: "A finishing environment for edit, grade and delivery—assembled around one cinematic frame.",
    assets: [demoMedia.filmFrame, demoMedia.workstation],
  },
  {
    type: "motion",
    label: "MOTION / SEQUENCE",
    heading: "A sequence you can feel.",
    description: "Frames, timing and motion detail arranged as one scroll-scrubbed visual sequence.",
    assets: [demoMedia.motionSequence, demoMedia.motion],
  },
  {
    type: "creative",
    label: "CREATIVE / COMPOSITING / CGI",
    heading: "Built beyond the capture.",
    description: "Layered environments, digital craft and AI-assisted production where the brief calls for a controlled composite.",
    assets: [demoMedia.compositingLayers, demoMedia.creative],
  },
] as const;

export const demoPortfolio = [
  {
    title: "Beauty / Detail",
    category: "Image post-production",
    scope: "Sample concept",
    summary: "A demonstration of natural texture, tonal control and editorial beauty finishing.",
    asset: demoMedia.beautyDetail,
  },
  {
    title: "Product / Form",
    category: "E-commerce + product",
    scope: "Sample concept",
    summary: "A clean product study focused on surface, edge, shadow and commercial consistency.",
    asset: demoMedia.product,
  },
  {
    title: "Motion / Atmosphere",
    category: "Motion + colour",
    scope: "Sample concept",
    summary: "A cinematic sequence demonstrating motion direction, colour and campaign-ready framing.",
    asset: demoMedia.filmFrame,
  },
  {
    title: "Jewelry / Light",
    category: "Jewelry + macro",
    scope: "Sample concept",
    summary: "A precision study of facets, reflections and controlled macro detail.",
    asset: demoMedia.gemstone,
  },
  {
    title: "Motion / Sequence",
    category: "Motion design",
    scope: "Sample concept",
    summary: "A four-frame study built around timing, continuity and material movement.",
    asset: demoMedia.motionSequence,
  },
  {
    title: "Creative / Layers",
    category: "Compositing + CGI",
    scope: "Sample concept",
    summary: "Glass, metal and tactile surfaces assembled into one controlled visual system.",
    asset: demoMedia.compositingLayers,
  },
] as const;

export const demoGallery = [
  demoMedia.beautyRaw,
  demoMedia.productMaterial,
  demoMedia.gemstone,
  demoMedia.motion,
  demoMedia.creativeMaterial,
  demoMedia.productPolished,
] as const;

export const demoServiceMedia = [
  demoMedia.beautyDetail,
  demoMedia.filmFrame,
  demoMedia.compositingLayers,
  demoMedia.productPolished,
  demoMedia.gemstone,
  demoMedia.workstation,
] as const;
