import Link from "next/link";
import { notFound } from "next/navigation";
import { publishAboutPage, saveAboutPage } from "@/app/admin/actions";
import { MediaPicker, type PickerMedia } from "@/components/admin/MediaPicker";
import { PageHeader, StatusBadge } from "@/components/admin/AdminPrimitives";
import { aboutSectionTypes, defaultAboutContent, type AboutContent, type AboutSectionType } from "@/content/about";
import { hasDatabaseUrl, prisma } from "@/lib/db/client";
import { ConfirmActionButton } from "@/components/admin/ConfirmActionButton";
import { EditorStateIndicator } from "@/components/admin/EditorStateIndicator";

function SectionControls({ type, enabled, order }: { type: AboutSectionType; enabled: boolean; order: number }) {
  return <div className="admin-section-controls"><label className="admin-check"><input type="checkbox" name="enabledSections" value={type} defaultChecked={enabled} /> Show section</label><label>Order<input type="number" name={`${type}Order`} min="0" max="20" defaultValue={order} /></label></div>;
}

export default async function AboutAdminPage() {
  if (!hasDatabaseUrl()) notFound();
  const [page, media, services] = await Promise.all([
    prisma.page.findUnique({ where: { slug: "about" }, include: { sections: { orderBy: { order: "asc" } }, revisions: { orderBy: { createdAt: "desc" }, take: 12, include: { author: { select: { name: true, email: true } } } } } }),
    prisma.media.findMany({ select: { id: true, filename: true, publicUrl: true, mediaType: true, alt: true, caption: true, width: true, height: true }, take: 120, orderBy: { createdAt: "desc" } }),
    prisma.service.findMany({ where: { status: "PUBLISHED" }, orderBy: [{ featuredOrder: "asc" }, { title: "asc" }] }),
  ]);
  if (!page) notFound();
  const content = structuredClone(defaultAboutContent) as AboutContent;
  const enabled = new Set<AboutSectionType>();
  for (const section of page.sections) if (aboutSectionTypes.includes(section.type as AboutSectionType) && section.content && typeof section.content === "object") { Object.assign(content[section.type as AboutSectionType], section.content); if (section.enabled) enabled.add(section.type as AboutSectionType); }
  if (!page.sections.some((section) => aboutSectionTypes.includes(section.type as AboutSectionType))) aboutSectionTypes.forEach((type) => enabled.add(type));
  const order = new Map(page.sections.map((section) => [section.type, section.order]));
  const latestPublished = page.revisions.find((revision) => revision.note === "about:published");
  const latestDraft = page.revisions.find((revision) => revision.note === "about:draft");
  const hasSavedDraft = Boolean(latestDraft && (!latestPublished || latestDraft.createdAt > latestPublished.createdAt));
  const items = media as PickerMedia[];
  const controls = (type: AboutSectionType) => <SectionControls type={type} enabled={enabled.has(type)} order={order.get(type) ?? aboutSectionTypes.indexOf(type)} />;
  return <section className="admin-content"><PageHeader eyebrow="CONTENT / STUDIO" title="About / Studio" description="Edit the saved draft, inspect the private preview, then publish. The public /about page remains on its last published revision until then." />
    <div className="admin-publication-summary"><StatusBadge value={page.status} /><span>{hasSavedDraft ? "Saved draft differs from the published page." : "Published version is current."}</span>{page.publishedAt && <small>Last published {page.publishedAt.toLocaleString()}</small>}<Link href="/admin/pages/about/preview" target="_blank">Open Draft Preview ↗</Link></div>
    <form action={saveAboutPage} className="admin-card admin-content-form admin-about-form"><input type="hidden" name="pageId" value={page.id} />
      <section><h2>SEO</h2><label>Admin page title<input name="title" defaultValue={page.title} required /></label><label>SEO title<input name="seoTitle" defaultValue={page.seoTitle ?? "Studio — PicVisual"} /></label><label>SEO description<textarea name="seoDescription" rows={3} defaultValue={page.seoDescription ?? "The production partner after the shoot—image, motion and commercial post-production by PicVisual."} /></label><MediaPicker name="ogImageId" label="Open Graph image" items={items} selectedId={page.ogImageId} accept="IMAGE" /></section>
      <section><h2>Hero</h2>{controls("hero")}<label>Eyebrow<input name="heroEyebrow" defaultValue={content.hero.eyebrow} required /></label><label>Headline<textarea name="heroHeadline" rows={3} defaultValue={content.hero.headline} required /></label><label>Body<textarea name="heroBody" rows={5} defaultValue={content.hero.body} required /></label><div className="admin-form-columns"><label>Primary CTA label<input name="heroPrimaryLabel" defaultValue={content.hero.primaryLabel} required /></label><label>Primary CTA URL<input name="heroPrimaryHref" defaultValue={content.hero.primaryHref} required /></label><label>Secondary CTA label<input name="heroSecondaryLabel" defaultValue={content.hero.secondaryLabel} required /></label><label>Secondary CTA URL<input name="heroSecondaryHref" defaultValue={content.hero.secondaryHref} required /></label></div><MediaPicker name="heroImageMediaId" label="Hero image" items={items} selectedId={content.hero.imageMediaId} accept="IMAGE" /><MediaPicker name="heroVideoMediaId" label="Hero video (takes priority over image)" items={items} selectedId={content.hero.videoMediaId} accept="VIDEO" /><MediaPicker name="heroPosterMediaId" label="Hero video poster" items={items} selectedId={content.hero.posterMediaId} accept="IMAGE" /></section>
      <section><h2>Who we are</h2>{controls("who")}<label>Eyebrow<input name="whoEyebrow" defaultValue={content.who.eyebrow} /></label><label>Heading<textarea name="whoHeading" rows={3} defaultValue={content.who.heading} /></label><label>Body<textarea name="whoBody" rows={7} defaultValue={content.who.body} /></label><MediaPicker name="whoMediaId" label="Feature image" items={items} selectedId={content.who.mediaId} accept="IMAGE" /></section>
      <section><h2>What happens after the shoot</h2>{controls("afterShoot")}<label>Eyebrow<input name="afterShootEyebrow" defaultValue={content.afterShoot.eyebrow} /></label><label>Heading<textarea name="afterShootHeading" rows={3} defaultValue={content.afterShoot.heading} /></label><label>Body<textarea name="afterShootBody" rows={6} defaultValue={content.afterShoot.body} /></label><MediaPicker name="afterShootMediaId" label="Editorial image" items={items} selectedId={content.afterShoot.mediaId} accept="IMAGE" /></section>
      <section><h2>Production approach</h2>{controls("approach")}<label>Eyebrow<input name="approachEyebrow" defaultValue={content.approach.eyebrow} /></label><label>Heading<input name="approachHeading" defaultValue={content.approach.heading} /></label><label>Body<textarea name="approachBody" rows={5} defaultValue={content.approach.body} /></label><label>Principles <small>One per line</small><textarea name="approachPrinciples" rows={8} defaultValue={content.approach.principles.join("\n")} /></label></section>
      <section><h2>Collaboration</h2>{controls("collaboration")}<label>Eyebrow<input name="collaborationEyebrow" defaultValue={content.collaboration.eyebrow} /></label><label>Heading<input name="collaborationHeading" defaultValue={content.collaboration.heading} /></label><label>Body<textarea name="collaborationBody" rows={5} defaultValue={content.collaboration.body} /></label><label>Audiences <small>One per line</small><textarea name="collaborationAudiences" rows={7} defaultValue={content.collaboration.audiences.join("\n")} /></label></section>
      <section><h2>Capabilities</h2>{controls("capabilities")}<label>Eyebrow<input name="capabilitiesEyebrow" defaultValue={content.capabilities.eyebrow} /></label><label>Heading<input name="capabilitiesHeading" defaultValue={content.capabilities.heading} /></label><label>Body<textarea name="capabilitiesBody" rows={4} defaultValue={content.capabilities.body} /></label><fieldset className="admin-service-options"><legend>Published services <small>Leave all unchecked to show every published service.</small></legend>{services.map((service) => <label className="admin-check" key={service.id}><input type="checkbox" name="serviceIds" value={service.id} defaultChecked={content.capabilities.serviceIds.includes(service.id)} /> {service.title}</label>)}</fieldset></section>
      <section><h2>Optional studio media</h2>{controls("studioMedia")}<label>Eyebrow<input name="studioMediaEyebrow" defaultValue={content.studioMedia.eyebrow} /></label><label>Heading<input name="studioMediaHeading" defaultValue={content.studioMedia.heading} /></label><label>Body<textarea name="studioMediaBody" rows={4} defaultValue={content.studioMedia.body} /></label><MediaPicker name="studioMediaId" label="Studio / editorial image" items={items} selectedId={content.studioMedia.mediaId} accept="IMAGE" /><MediaPicker name="studioMotionMediaId" label="Optional motion / video" items={items} selectedId={content.studioMedia.motionMediaId} accept="VIDEO" /><MediaPicker name="studioPosterMediaId" label="Video poster" items={items} selectedId={content.studioMedia.posterMediaId} accept="IMAGE" /></section>
      <section><h2>Workflow</h2>{controls("workflow")}<label>Eyebrow<input name="workflowEyebrow" defaultValue={content.workflow.eyebrow} /></label><label>Heading<input name="workflowHeading" defaultValue={content.workflow.heading} /></label><label>Body<textarea name="workflowBody" rows={4} defaultValue={content.workflow.body} /></label><label>Steps <small>One per line</small><textarea name="workflowSteps" rows={6} defaultValue={content.workflow.steps.join("\n")} /></label></section>
      <section><h2>Final CTA</h2>{controls("cta")}<label>Eyebrow<input name="ctaEyebrow" defaultValue={content.cta.eyebrow} /></label><label>Heading<input name="ctaHeading" defaultValue={content.cta.heading} /></label><label>Body<input name="ctaBody" defaultValue={content.cta.body} /></label><div className="admin-form-columns"><label>Primary CTA label<input name="ctaPrimaryLabel" defaultValue={content.cta.primaryLabel} required /></label><label>Primary CTA URL<input name="ctaPrimaryHref" defaultValue={content.cta.primaryHref} required /></label><label>Secondary CTA label<input name="ctaSecondaryLabel" defaultValue={content.cta.secondaryLabel} required /></label><label>Secondary CTA URL<input name="ctaSecondaryHref" defaultValue={content.cta.secondaryHref} required /></label></div></section>
      <div className="admin-sticky-actions"><EditorStateIndicator initialState={hasSavedDraft ? "SAVED DRAFT" : "PUBLISHED"} /><button name="intent" value="draft">Save Draft</button><Link href="/admin/pages/about/preview" target="_blank">Preview saved draft ↗</Link><ConfirmActionButton action={publishAboutPage} message="Publish this saved content? This will update the public website.">Publish</ConfirmActionButton></div>
    </form>
    <div className="admin-card"><h2>Revision history</h2>{page.revisions.length ? <div className="admin-record-list">{page.revisions.map((revision) => <article key={revision.id}><div><strong>{revision.note || "Page revision"}</strong><span>{revision.createdAt.toLocaleString()} · {revision.author?.name || revision.author?.email || "System"}</span></div></article>)}</div> : <p>No About revisions yet.</p>}<small>Published revisions remain frozen. Historical content never republishes itself.</small></div>
  </section>;
}
