const {chromium,expect}=require('@playwright/test');const{PrismaClient}=require('@prisma/client');const fs=require('node:fs');const db=new PrismaClient();const base='http://localhost:3000';const results=[];const pass=name=>{results.push({name,status:'PASS'});console.log('PASS',name)};
(async()=>{const browser=await chromium.launch({channel:'chrome',headless:true});const admin=await browser.newPage();const anon=await browser.newPage();admin.setDefaultNavigationTimeout(90000);anon.setDefaultNavigationTimeout(90000);const original=await db.page.findUnique({where:{slug:'home'},include:{sections:true}});const baseline=await db.pageRevision.findFirstOrThrow({where:{pageId:original.id,note:'homepage:published'},orderBy:{createdAt:'desc'}});let published=false;
try{
 await admin.goto(base+'/admin/login');await admin.getByLabel('Work email').fill(process.env.ADMIN_EMAIL);await admin.getByLabel('Password',{exact:true}).fill(process.env.ADMIN_INITIAL_PASSWORD);await admin.getByRole('button',{name:'Sign in',exact:true}).click();await expect(admin).toHaveURL(base+'/admin');
 await admin.goto(base+'/admin/homepage');let hero=admin.locator('form').filter({has:admin.locator('input[name=type][value=hero]')});await hero.getByLabel('Heading',{exact:true}).fill('Private lifecycle verification');await hero.getByRole('button',{name:'Save draft',exact:true}).click();await admin.waitForURL(/success=draft-saved/);const privateRevision=await db.pageRevision.findFirstOrThrow({where:{pageId:original.id,note:'homepage:draft'},orderBy:{createdAt:'desc'}});
 await admin.goto(base+"/admin/homepage");
 const workflow=admin.locator('.admin-section-editor').filter({has:admin.locator('input[name=type][value=productionWorkflow]')});await workflow.getByRole('button',{name:'Move down',exact:true}).click();await admin.waitForURL(/success=draft-saved/);await admin.goto(base+'/admin/homepage/preview');const order=await admin.locator('.reasons,.system').evaluateAll(els=>els.map(el=>el.className));if(order[0]!=='reasons')throw Error('Draft order ignored');pass('Homepage draft ordering renders');
 await admin.goto(base+'/admin/homepage');const optional=admin.locator('form').filter({has:admin.locator('input[name=type][value=motionShowcase]')});await optional.getByLabel('Show section').uncheck();await optional.getByRole('button',{name:'Save draft',exact:true}).click();await admin.waitForURL(/success=draft-saved/);await admin.goto(base+'/admin/homepage/preview');await expect(admin.locator('.motion-showcase')).toHaveCount(0);await anon.goto(base);await expect(anon.locator('.motion-showcase')).toHaveCount(1);pass('Homepage visibility draft isolation');
 await admin.goto(base+'/admin/homepage');admin.once('dialog',d=>d.accept());await admin.getByRole('button',{name:'Publish',exact:true}).click();await admin.waitForURL(/success=published/);published=true;await anon.goto(base);await expect(anon.locator('h1')).toHaveText('Private lifecycle verification');await expect(anon.locator('.motion-showcase')).toHaveCount(0);pass('Homepage explicit publish content and visibility');
 const restore=admin.locator('form').filter({has:admin.locator(`input[name=revisionId][value="${privateRevision.id}"]`)});await restore.getByRole('button',{name:'Restore to draft'}).click();await admin.waitForURL(/success=revision-restored-to-draft/);await admin.goto(base+'/admin/homepage/preview');await expect(admin.locator('.motion-showcase')).toHaveCount(1);await anon.goto(base);await expect(anon.locator('.motion-showcase')).toHaveCount(0);pass('Homepage revision history and restore stay private');
}finally{
 // Restore the exact local draft and approved publication; fixtures never reach deployment.
 await db.$transaction(async tx=>{await tx.pageSection.deleteMany({where:{pageId:original.id}});await tx.pageSection.createMany({data:original.sections});if(published)await tx.pageRevision.create({data:{pageId:original.id,note:'homepage:published',snapshot:baseline.snapshot}});});
 if(published){await admin.goto(base+'/admin/homepage');admin.once('dialog',d=>d.accept());await admin.getByRole('button',{name:'Publish',exact:true}).click();await admin.waitForURL(/success=published/);}
 fs.writeFileSync('artifacts/browser/homepage-e2e.json',JSON.stringify(results,null,2));await browser.close();await db.$disconnect();}
})().catch(e=>{console.error('FAIL',e.message);process.exit(1)});
