const { chromium, expect } = require('@playwright/test');
const { PrismaClient } = require('@prisma/client');
const fs = require('node:fs');
const db = new PrismaClient(); const results=[]; const prefix=`launch-qa-${Date.now()}`; const base='http://localhost:3000';
const pass=(name)=>{results.push({name,status:'PASS'});console.log('PASS',name)};
(async()=>{
 if(!['localhost','127.0.0.1'].includes(new URL(process.env.DATABASE_URL).hostname))throw Error('Local QA database required');
 await db.rateLimit.deleteMany({where:{key:{startsWith:'login'}}});
 const browser=await chromium.launch({channel:'chrome',headless:true});const context=await browser.newContext({viewport:{width:1440,height:900}});const admin=await context.newPage();const anon=await browser.newPage();admin.setDefaultNavigationTimeout(90000);anon.setDefaultNavigationTimeout(90000);let projectId, serviceId, enquiryId;let originalHero;
 try {
  await anon.goto(`${base}/admin/projects`);await expect(anon).toHaveURL(/\/admin\/login/);pass('Unauthenticated protected redirect');
  await admin.goto(`${base}/admin/login`);await admin.getByLabel('Work email').fill(process.env.ADMIN_EMAIL);await admin.getByLabel('Password',{exact:true}).fill('wrong-password-fixture');await admin.getByRole('button',{name:'Sign in',exact:true}).click();await expect(admin.locator('.admin-error')).toContainText('Invalid email or password');pass('Wrong password rejection');
  await admin.getByLabel('Work email').fill(process.env.ADMIN_EMAIL);await admin.getByLabel('Password',{exact:true}).fill(process.env.ADMIN_INITIAL_PASSWORD);await admin.getByRole('button',{name:'Sign in',exact:true}).click();await expect(admin).toHaveURL(`${base}/admin`);pass('OWNER login');
  for(const route of ['/admin/homepage','/admin/projects','/admin/services','/admin/media','/admin/faq','/admin/enquiries','/admin/clients','/admin/testimonials','/admin/navigation','/admin/settings','/admin/settings/branding','/admin/users','/admin/account']){const r=await admin.goto(base+route);if(r.status()!==200)throw Error(`${route} returned ${r.status()}`);await expect(admin.locator('main, .admin-main').first()).toBeVisible();}pass('All admin pages render');
  await admin.goto(`${base}/admin/projects`);const create=admin.locator('form').filter({has:admin.getByRole('heading',{name:'New project'})});await create.getByLabel('Title',{exact:true}).fill(prefix);await create.getByLabel('Slug',{exact:true}).fill(prefix);await create.getByLabel('Category',{exact:true}).fill('Internal QA');await create.getByLabel('Summary',{exact:true}).fill('Disposable local publication isolation fixture.');await create.getByRole('button',{name:'Create draft'}).click();await admin.waitForURL(/\/admin\/projects\/[^/?]+\?success=draft-saved/);projectId=new URL(admin.url()).pathname.split('/').pop();
  let r=await anon.goto(`${base}/work/${prefix}`);if(r.status()!==404)throw Error('Draft project publicly visible');pass('Project create and anonymous draft exclusion');
  await admin.getByRole('button',{name:'Publish',exact:true}).click();await admin.waitForURL(/success=published/);await anon.goto(`${base}/work/${prefix}`);await expect(anon.locator('h1')).toHaveText(prefix);pass('Project explicit publish');
  await admin.getByLabel('Title',{exact:true}).fill(`${prefix} draft-only`);await admin.getByLabel('Slug',{exact:true}).fill(`${prefix}-new`);await admin.getByRole('button',{name:'Save draft',exact:true}).click();await admin.waitForURL(/success=draft-saved/);await anon.goto(`${base}/work/${prefix}`);await expect(anon.locator('h1')).toHaveText(prefix);r=await anon.goto(`${base}/work/${prefix}-new`);if(r.status()!==404)throw Error('Draft slug leaked');
  await admin.goto(`${base}/admin/projects/${projectId}/preview`);await expect(admin.locator('h1')).toHaveText(`${prefix} draft-only`);pass('Project draft title and slug isolation; secure preview');
  await admin.goto(`${base}/admin/projects/${projectId}`);const galleryForm=admin.locator('form').filter({has:admin.getByRole('button',{name:'Add gallery media',exact:true})});await galleryForm.getByRole('button',{name:'Choose from media library'}).click();await admin.getByRole('dialog').getByRole('button').filter({hasText:'CHAMOIS_CH03_3.jpg'}).click();await galleryForm.getByRole('button',{name:'Add gallery media',exact:true}).click();await admin.waitForURL(/success=gallery-added/);await anon.goto(`${base}/work/${prefix}`);await expect(anon.locator('.case-gallery')).toHaveCount(0);await admin.goto(`${base}/admin/projects/${projectId}/preview`);await expect(admin.locator('.case-gallery img')).toHaveCount(1);pass('Project gallery draft isolation');
  await admin.goto(`${base}/admin/projects/${projectId}`);await admin.getByLabel('Slug',{exact:true}).fill(prefix);await admin.getByRole('button',{name:'Publish',exact:true}).click();await admin.waitForURL(/success=published/);await anon.goto(`${base}/work/${prefix}`);await expect(anon.locator('h1')).toHaveText(`${prefix} draft-only`);await expect(anon.locator('.case-gallery img')).toHaveCount(1);pass('Project draft and gallery publish together');
  await admin.getByRole('button',{name:'Archive',exact:true}).click();await admin.waitForURL(/success=archived/);r=await anon.goto(`${base}/work/${prefix}`);if(r.status()!==404)throw Error('Archived project leaked');pass('Project archive exclusion');
  await admin.goto(`${base}/admin/services`);const service=admin.locator('form').filter({has:admin.getByRole('heading',{name:'New service',exact:true})});await service.getByLabel('Title',{exact:true}).fill(prefix);await service.getByLabel('Slug',{exact:true}).fill(prefix);await service.getByLabel('Short label / category').fill('Internal QA');await service.getByLabel('Summary',{exact:true}).fill('Disposable local service publication fixture.');await service.getByRole('button',{name:'Publish',exact:true}).click();await admin.waitForURL(/success=published/);serviceId=(await db.service.findUnique({where:{slug:prefix}})).id;await anon.goto(`${base}/services`);await expect(anon.getByRole('heading',{name:prefix,exact:true})).toBeVisible();
  let article=admin.locator('article').filter({has:admin.locator('strong').filter({hasText:prefix})});await article.locator('summary').click();await article.getByLabel('Title',{exact:true}).fill(`${prefix} draft-only`);await article.getByRole('button',{name:'Save draft',exact:true}).click();await admin.waitForURL(/success=draft-saved/);await anon.goto(`${base}/services`);await expect(anon.getByRole('heading',{name:prefix,exact:true})).toBeVisible();await expect(anon.getByRole('heading',{name:`${prefix} draft-only`,exact:true})).toHaveCount(0);await admin.goto(`${base}/admin/services/${serviceId}/preview`);await expect(admin.locator('h1')).toHaveText(`${prefix} draft-only`);pass('Service publish, draft isolation and secure preview');
  await admin.goto(`${base}/admin/services`);article=admin.locator('article').filter({has:admin.locator('strong').filter({hasText:prefix})});await article.locator('summary').click();await article.getByRole('button',{name:'Publish',exact:true}).click();await admin.waitForURL(/success=published/);await anon.goto(`${base}/services`);await expect(anon.getByRole('heading',{name:`${prefix} draft-only`,exact:true})).toBeVisible();pass('Service explicit republish');
  await admin.goto(`${base}/admin/homepage`);const hero=admin.locator('form').filter({has:admin.locator('input[name="type"][value="hero"]')});await hero.getByLabel('Show section').check();originalHero=await hero.getByLabel('Heading',{exact:true}).inputValue();await hero.getByLabel('Heading',{exact:true}).fill('Private homepage draft QA');await hero.getByRole('button',{name:'Save draft',exact:true}).click();await admin.waitForURL(/success=draft-saved/);await anon.goto(base);await expect(anon.locator('h1')).not.toHaveText('Private homepage draft QA');await admin.goto(`${base}/admin/homepage/preview`);await expect(admin.locator('h1')).toHaveText('Private homepage draft QA');pass('Homepage draft persistence, anonymous isolation, actual-component preview');
  await admin.goto(`${base}/admin/homepage`);const heroAgain=admin.locator('form').filter({has:admin.locator('input[name="type"][value="hero"]')});await heroAgain.getByLabel('Heading',{exact:true}).fill(originalHero);await heroAgain.getByRole('button',{name:'Save draft',exact:true}).click();await admin.waitForURL(/success=draft-saved/);originalHero=undefined;
  await anon.goto(`${base}/contact`);await anon.getByLabel('Name',{exact:true}).fill('Local Launch QA');await anon.getByLabel('Work email',{exact:true}).fill(`${prefix}@example.invalid`);await anon.getByLabel('Company / brand').fill('Disposable local fixture');await anon.getByLabel('Project type').selectOption('Image post-production');await anon.getByLabel('Tell us about the work').fill('Clearly labelled disposable local contact-to-CRM test enquiry.');await anon.waitForTimeout(1600);await anon.getByRole('button',{name:'Start the conversation'}).click();await expect(anon.getByRole('status')).toContainText('received');enquiryId=(await db.contactSubmission.findFirstOrThrow({where:{email:`${prefix}@example.invalid`}})).id;await admin.goto(`${base}/admin/enquiries?q=${prefix}`);await admin.getByRole('link',{name:'Local Launch QA'}).click();await admin.getByLabel('Internal notes').fill('Verified by the local launch regression test.');await admin.locator('select[name=status]').selectOption('REPLIED');await admin.getByLabel('Archive this enquiry').check();await admin.getByRole('button',{name:'Save enquiry'}).click();await admin.waitForURL(/success=saved/);const enquiry=await db.contactSubmission.findUnique({where:{id:enquiryId}});if(!enquiry.archivedAt||enquiry.status!=='REPLIED'||!enquiry.internalNotes)throw Error('CRM update not persisted');pass('Contact to CRM, notes, status and archive');
  await admin.getByRole('button',{name:'Sign out'}).click();await expect(admin).toHaveURL(/\/admin\/login/);await admin.goto(`${base}/admin`);await expect(admin).toHaveURL(/\/admin\/login/);pass('Logout');
 } finally {
  if(originalHero){const home=await db.page.findUnique({where:{slug:'home'}});const row=await db.pageSection.findFirst({where:{pageId:home.id,type:'hero'}});await db.pageSection.update({where:{id:row.id},data:{content:{...row.content,headline:originalHero}}});}
  if(projectId){await db.projectMedia.deleteMany({where:{projectId}});await db.project.delete({where:{id:projectId}})}
  if(serviceId)await db.service.delete({where:{id:serviceId}});
  if(enquiryId)await db.contactSubmission.delete({where:{id:enquiryId}});
  await db.auditLog.deleteMany({where:{entityId:{in:[projectId,serviceId,enquiryId].filter(Boolean)}}});
  fs.writeFileSync('artifacts/browser/runtime-e2e.json',JSON.stringify(results,null,2));await browser.close();await db.$disconnect();
 }
})().catch(e=>{console.error('FAIL',e.message);process.exit(1)});
