const{chromium,expect}=require('@playwright/test');const{PrismaClient}=require('@prisma/client');const bcrypt=require('bcryptjs');const{randomUUID}=require('node:crypto');const fs=require('node:fs');const db=new PrismaClient();const base='http://localhost:3000';const results=[];const pass=name=>{results.push({name,status:'PASS'});console.log('PASS',name)};
(async()=>{if(!['localhost','127.0.0.1'].includes(new URL(process.env.DATABASE_URL).hostname))throw Error('Local QA database required');const browser=await chromium.launch({channel:'chrome',headless:true});const context=await browser.newContext();const page=await context.newPage();const email=`internal-security-${Date.now()}@example.invalid`;const password=randomUUID()+'Aa1!';let user;
try{
 for(const route of ['/api/admin/media','/api/admin/media/direct']){const response=route.endsWith('direct')?await page.request.post(base+route,{data:{filename:'test.png',mimeType:'image/png',fileSize:30}}):await page.request.get(base+route);if(![401,403].includes(response.status()))throw Error('Anonymous media API not protected');}pass('Unauthenticated media APIs reject requests');
 user=await db.user.create({data:{email,passwordHash:await bcrypt.hash(password,12),name:'Disposable security QA',role:'EDITOR'}});
 await page.goto(base+'/admin/login');await page.getByLabel('Work email').fill(email);await page.getByLabel('Password',{exact:true}).fill(password);await page.getByRole('button',{name:'Sign in',exact:true}).click();await expect(page).toHaveURL(base+'/admin');const cookies=await context.cookies();const session=cookies.find(c=>c.httpOnly);if(!session||session.sameSite!=='Lax'||session.expires<Date.now()/1000)throw Error('Session cookie policy failed');pass('EDITOR authentication and httpOnly expiring SameSite session');
 for(const route of ['/admin/users','/admin/settings','/admin/settings/branding']){await page.goto(base+route);await expect(page).toHaveURL(/\/admin\?error=unauthorized/);}await page.goto(base+'/admin/projects');await expect(page.getByRole('heading',{name:'Projects',exact:true})).toBeVisible();pass('EDITOR content access and settings/user permission denial');
 const stale=await browser.newContext();await stale.addCookies(cookies);const oldPage=await stale.newPage();await page.goto(base+'/admin/account');await page.getByLabel('Current password').fill(password);await page.getByLabel('New password',{exact:true}).fill(password+'new');await page.getByLabel('Confirm new password').fill(password+'new');await page.getByRole('button',{name:'Change password',exact:true}).click();await expect(page).toHaveURL(/\/admin\/login/);await oldPage.goto(base+'/admin');await expect(oldPage).toHaveURL(/\/admin\/login/);await stale.close();pass('Password change invalidates current and previously issued sessions');
 await page.getByLabel('Work email').fill(email);await page.getByLabel('Password',{exact:true}).fill(password+'new');await page.getByRole('button',{name:'Sign in',exact:true}).click();await expect(page).toHaveURL(base+'/admin');await db.user.update({where:{id:user.id},data:{isActive:false}});await page.goto(base+'/admin');await expect(page).toHaveURL(/\/admin\/login/);pass('Deactivated accounts lose existing session access');
 const owner=await browser.newPage();await owner.goto(base+'/admin/login');await owner.getByLabel('Work email').fill(process.env.ADMIN_EMAIL);await owner.getByLabel('Password',{exact:true}).fill(process.env.ADMIN_INITIAL_PASSWORD);await owner.getByRole('button',{name:'Sign in',exact:true}).click();await expect(owner).toHaveURL(base+'/admin');await owner.goto(base+'/admin/users');const record=await db.user.findUniqueOrThrow({where:{email:process.env.ADMIN_EMAIL}});const access=owner.locator('form').filter({has:owner.locator(`input[name=id][value="${record.id}"]`)});await access.locator('select[name=role]').selectOption('ADMIN');await access.getByRole('button',{name:'Save access'}).click();await owner.waitForURL(/error=last-owner/);if((await db.user.findUnique({where:{id:record.id}})).role!=='OWNER')throw Error('Last owner was demoted');pass('Last active OWNER demotion blocked by server');await owner.getByRole('button',{name:'Sign out'}).click();await expect(owner).toHaveURL(/\/admin\/login/);await owner.goto(base+'/admin');await expect(owner).toHaveURL(/\/admin\/login/);pass('OWNER logout clears access');
 const anon=await browser.newPage();const response=await anon.goto(base+'/admin/homepage/preview');await expect(anon).toHaveURL(/\/admin\/login/);if(!response.headers()['x-robots-tag']?.includes('noindex'))throw Error('Admin robots header missing');pass('Preview auth and admin noindex header');
}finally{if(user){await db.auditLog.deleteMany({where:{OR:[{userId:user.id},{entityId:user.id}]}});await db.user.delete({where:{id:user.id}});}fs.writeFileSync('artifacts/browser/security-e2e.json',JSON.stringify(results,null,2));await browser.close();await db.$disconnect();}
})().catch(e=>{console.error('FAIL',e.message);process.exit(1)});
