-- Initial PicVisual CMS foundation. Generated from prisma/schema.prisma for PostgreSQL.
CREATE TYPE "Role" AS ENUM ('OWNER', 'ADMIN', 'EDITOR');
CREATE TYPE "PageStatus" AS ENUM ('DRAFT', 'PUBLISHED', 'HIDDEN');
CREATE TYPE "ProjectStatus" AS ENUM ('DRAFT', 'PUBLISHED', 'ARCHIVED');
CREATE TYPE "ServiceStatus" AS ENUM ('DRAFT', 'PUBLISHED', 'ARCHIVED');
CREATE TYPE "MediaType" AS ENUM ('IMAGE', 'VIDEO');
CREATE TYPE "ContactStatus" AS ENUM ('NEW', 'IN_PROGRESS', 'REPLIED', 'CLOSED');
CREATE TYPE "NavigationKind" AS ENUM ('HEADER', 'FOOTER', 'CUSTOM');
CREATE TYPE "ProjectMediaRole" AS ENUM ('GALLERY', 'DETAIL', 'MOTION_STILL');

CREATE TABLE "User" ("id" TEXT NOT NULL,"name" TEXT,"email" TEXT NOT NULL,"passwordHash" TEXT NOT NULL,"role" "Role" NOT NULL DEFAULT 'EDITOR',"isActive" BOOLEAN NOT NULL DEFAULT true,"createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,"updatedAt" TIMESTAMP(3) NOT NULL,"lastLoginAt" TIMESTAMP(3),CONSTRAINT "User_pkey" PRIMARY KEY ("id"));
CREATE TABLE "Page" ("id" TEXT NOT NULL,"title" TEXT NOT NULL,"slug" TEXT NOT NULL,"pageType" TEXT NOT NULL,"status" "PageStatus" NOT NULL DEFAULT 'DRAFT',"seoTitle" TEXT,"seoDescription" TEXT,"canonicalUrl" TEXT,"indexable" BOOLEAN NOT NULL DEFAULT true,"ogImageId" TEXT,"publishedAt" TIMESTAMP(3),"createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,"updatedAt" TIMESTAMP(3) NOT NULL,CONSTRAINT "Page_pkey" PRIMARY KEY ("id"));
CREATE TABLE "PageSection" ("id" TEXT NOT NULL,"pageId" TEXT NOT NULL,"type" TEXT NOT NULL,"order" INTEGER NOT NULL,"enabled" BOOLEAN NOT NULL DEFAULT true,"theme" TEXT,"content" JSONB NOT NULL,"settings" JSONB,"createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,"updatedAt" TIMESTAMP(3) NOT NULL,CONSTRAINT "PageSection_pkey" PRIMARY KEY ("id"));
CREATE TABLE "PageRevision" ("id" TEXT NOT NULL,"pageId" TEXT NOT NULL,"authorId" TEXT,"snapshot" JSONB NOT NULL,"note" TEXT,"createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,CONSTRAINT "PageRevision_pkey" PRIMARY KEY ("id"));
CREATE TABLE "Media" ("id" TEXT NOT NULL,"filename" TEXT NOT NULL,"originalFilename" TEXT NOT NULL,"storageProvider" TEXT NOT NULL,"storageKey" TEXT NOT NULL,"publicUrl" TEXT NOT NULL,"mimeType" TEXT NOT NULL,"mediaType" "MediaType" NOT NULL,"width" INTEGER,"height" INTEGER,"duration" DOUBLE PRECISION,"fileSize" INTEGER,"alt" TEXT,"caption" TEXT,"focalX" INTEGER DEFAULT 50,"focalY" INTEGER DEFAULT 50,"posterMediaId" TEXT,"createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,"updatedAt" TIMESTAMP(3) NOT NULL,CONSTRAINT "Media_pkey" PRIMARY KEY ("id"));
CREATE TABLE "Project" ("id" TEXT NOT NULL,"slug" TEXT NOT NULL,"title" TEXT NOT NULL,"category" TEXT NOT NULL,"summary" TEXT NOT NULL,"description" TEXT,"status" "ProjectStatus" NOT NULL DEFAULT 'DRAFT',"featured" BOOLEAN NOT NULL DEFAULT false,"featuredOrder" INTEGER,"year" INTEGER,"clientName" TEXT,"services" TEXT[],"heroMediaId" TEXT,"thumbnailMediaId" TEXT,"beforeMediaId" TEXT,"afterMediaId" TEXT,"videoMediaId" TEXT,"videoPosterMediaId" TEXT,"ogImageId" TEXT,"seoTitle" TEXT,"seoDescription" TEXT,"createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,"updatedAt" TIMESTAMP(3) NOT NULL,"publishedAt" TIMESTAMP(3),CONSTRAINT "Project_pkey" PRIMARY KEY ("id"));
CREATE TABLE "ProjectMedia" ("id" TEXT NOT NULL,"projectId" TEXT NOT NULL,"mediaId" TEXT NOT NULL,"order" INTEGER NOT NULL,"role" "ProjectMediaRole" NOT NULL DEFAULT 'GALLERY',"caption" TEXT,"alt" TEXT,CONSTRAINT "ProjectMedia_pkey" PRIMARY KEY ("id"));
CREATE TABLE "Service" ("id" TEXT NOT NULL,"slug" TEXT NOT NULL,"title" TEXT NOT NULL,"category" TEXT NOT NULL,"shortDescription" TEXT NOT NULL,"description" TEXT,"featured" BOOLEAN NOT NULL DEFAULT false,"featuredOrder" INTEGER,"status" "ServiceStatus" NOT NULL DEFAULT 'DRAFT',"heroMediaId" TEXT,"thumbnailMediaId" TEXT,"seoTitle" TEXT,"seoDescription" TEXT,"createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,"updatedAt" TIMESTAMP(3) NOT NULL,"ogImageId" TEXT,CONSTRAINT "Service_pkey" PRIMARY KEY ("id"));
CREATE TABLE "FAQ" ("id" TEXT NOT NULL,"question" TEXT NOT NULL,"answer" TEXT NOT NULL,"order" INTEGER NOT NULL,"enabled" BOOLEAN NOT NULL DEFAULT true,"pageKey" TEXT,"createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,"updatedAt" TIMESTAMP(3) NOT NULL,CONSTRAINT "FAQ_pkey" PRIMARY KEY ("id"));
CREATE TABLE "Testimonial" ("id" TEXT NOT NULL,"quote" TEXT NOT NULL,"person" TEXT,"role" TEXT,"company" TEXT,"mediaId" TEXT,"order" INTEGER NOT NULL,"enabled" BOOLEAN NOT NULL DEFAULT true,"createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,"updatedAt" TIMESTAMP(3) NOT NULL,CONSTRAINT "Testimonial_pkey" PRIMARY KEY ("id"));
CREATE TABLE "Client" ("id" TEXT NOT NULL,"name" TEXT NOT NULL,"logoMediaId" TEXT,"website" TEXT,"order" INTEGER NOT NULL,"enabled" BOOLEAN NOT NULL DEFAULT true,"createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,"updatedAt" TIMESTAMP(3) NOT NULL,CONSTRAINT "Client_pkey" PRIMARY KEY ("id"));
CREATE TABLE "Navigation" ("id" TEXT NOT NULL,"name" TEXT NOT NULL,"kind" "NavigationKind" NOT NULL,"createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,"updatedAt" TIMESTAMP(3) NOT NULL,CONSTRAINT "Navigation_pkey" PRIMARY KEY ("id"));
CREATE TABLE "NavigationItem" ("id" TEXT NOT NULL,"navigationId" TEXT NOT NULL,"parentId" TEXT,"label" TEXT NOT NULL,"href" TEXT NOT NULL,"order" INTEGER NOT NULL,"enabled" BOOLEAN NOT NULL DEFAULT true,"openInNewTab" BOOLEAN NOT NULL DEFAULT false,CONSTRAINT "NavigationItem_pkey" PRIMARY KEY ("id"));
CREATE TABLE "SiteSetting" ("id" TEXT NOT NULL,"key" TEXT NOT NULL,"value" JSONB NOT NULL,"logoMediaId" TEXT,"createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,"updatedAt" TIMESTAMP(3) NOT NULL,CONSTRAINT "SiteSetting_pkey" PRIMARY KEY ("id"));
CREATE TABLE "ContactSubmission" ("id" TEXT NOT NULL,"name" TEXT NOT NULL,"email" TEXT NOT NULL,"company" TEXT,"projectType" TEXT,"estimatedVolume" TEXT,"timeline" TEXT,"budgetRange" TEXT,"message" TEXT,"status" "ContactStatus" NOT NULL DEFAULT 'NEW',"createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,"updatedAt" TIMESTAMP(3) NOT NULL,CONSTRAINT "ContactSubmission_pkey" PRIMARY KEY ("id"));
CREATE TABLE "AuditLog" ("id" TEXT NOT NULL,"userId" TEXT,"action" TEXT NOT NULL,"entityType" TEXT NOT NULL,"entityId" TEXT,"metadata" JSONB,"createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,CONSTRAINT "AuditLog_pkey" PRIMARY KEY ("id"));

CREATE UNIQUE INDEX "User_email_key" ON "User"("email");
CREATE UNIQUE INDEX "Page_slug_key" ON "Page"("slug");
CREATE INDEX "Page_status_idx" ON "Page"("status");
CREATE INDEX "PageSection_pageId_enabled_idx" ON "PageSection"("pageId", "enabled");
CREATE UNIQUE INDEX "PageSection_pageId_order_key" ON "PageSection"("pageId", "order");
CREATE INDEX "PageRevision_pageId_createdAt_idx" ON "PageRevision"("pageId", "createdAt");
CREATE UNIQUE INDEX "Media_storageKey_key" ON "Media"("storageKey");
CREATE INDEX "Media_createdAt_idx" ON "Media"("createdAt");
CREATE INDEX "Media_mediaType_idx" ON "Media"("mediaType");
CREATE UNIQUE INDEX "Project_slug_key" ON "Project"("slug");
CREATE INDEX "Project_status_idx" ON "Project"("status");
CREATE INDEX "Project_featured_idx" ON "Project"("featured");
CREATE UNIQUE INDEX "ProjectMedia_projectId_mediaId_key" ON "ProjectMedia"("projectId", "mediaId");
CREATE UNIQUE INDEX "ProjectMedia_projectId_order_key" ON "ProjectMedia"("projectId", "order");
CREATE UNIQUE INDEX "Service_slug_key" ON "Service"("slug");
CREATE INDEX "Service_status_idx" ON "Service"("status");
CREATE UNIQUE INDEX "FAQ_pageKey_order_key" ON "FAQ"("pageKey", "order");
CREATE UNIQUE INDEX "Navigation_kind_key" ON "Navigation"("kind");
CREATE UNIQUE INDEX "NavigationItem_navigationId_order_key" ON "NavigationItem"("navigationId", "order");
CREATE UNIQUE INDEX "SiteSetting_key_key" ON "SiteSetting"("key");
CREATE INDEX "ContactSubmission_status_idx" ON "ContactSubmission"("status");
CREATE INDEX "AuditLog_createdAt_idx" ON "AuditLog"("createdAt");

ALTER TABLE "Page" ADD CONSTRAINT "Page_ogImageId_fkey" FOREIGN KEY ("ogImageId") REFERENCES "Media"("id") ON DELETE SET NULL ON UPDATE CASCADE;
ALTER TABLE "PageSection" ADD CONSTRAINT "PageSection_pageId_fkey" FOREIGN KEY ("pageId") REFERENCES "Page"("id") ON DELETE RESTRICT ON UPDATE CASCADE;
ALTER TABLE "PageRevision" ADD CONSTRAINT "PageRevision_pageId_fkey" FOREIGN KEY ("pageId") REFERENCES "Page"("id") ON DELETE RESTRICT ON UPDATE CASCADE;
ALTER TABLE "PageRevision" ADD CONSTRAINT "PageRevision_authorId_fkey" FOREIGN KEY ("authorId") REFERENCES "User"("id") ON DELETE SET NULL ON UPDATE CASCADE;
ALTER TABLE "Media" ADD CONSTRAINT "Media_posterMediaId_fkey" FOREIGN KEY ("posterMediaId") REFERENCES "Media"("id") ON DELETE SET NULL ON UPDATE CASCADE;
ALTER TABLE "Project" ADD CONSTRAINT "Project_heroMediaId_fkey" FOREIGN KEY ("heroMediaId") REFERENCES "Media"("id") ON DELETE SET NULL ON UPDATE CASCADE;
ALTER TABLE "Project" ADD CONSTRAINT "Project_thumbnailMediaId_fkey" FOREIGN KEY ("thumbnailMediaId") REFERENCES "Media"("id") ON DELETE SET NULL ON UPDATE CASCADE;
ALTER TABLE "Project" ADD CONSTRAINT "Project_beforeMediaId_fkey" FOREIGN KEY ("beforeMediaId") REFERENCES "Media"("id") ON DELETE SET NULL ON UPDATE CASCADE;
ALTER TABLE "Project" ADD CONSTRAINT "Project_afterMediaId_fkey" FOREIGN KEY ("afterMediaId") REFERENCES "Media"("id") ON DELETE SET NULL ON UPDATE CASCADE;
ALTER TABLE "Project" ADD CONSTRAINT "Project_videoMediaId_fkey" FOREIGN KEY ("videoMediaId") REFERENCES "Media"("id") ON DELETE SET NULL ON UPDATE CASCADE;
ALTER TABLE "Project" ADD CONSTRAINT "Project_videoPosterMediaId_fkey" FOREIGN KEY ("videoPosterMediaId") REFERENCES "Media"("id") ON DELETE SET NULL ON UPDATE CASCADE;
ALTER TABLE "Project" ADD CONSTRAINT "Project_ogImageId_fkey" FOREIGN KEY ("ogImageId") REFERENCES "Media"("id") ON DELETE SET NULL ON UPDATE CASCADE;
ALTER TABLE "ProjectMedia" ADD CONSTRAINT "ProjectMedia_projectId_fkey" FOREIGN KEY ("projectId") REFERENCES "Project"("id") ON DELETE RESTRICT ON UPDATE CASCADE;
ALTER TABLE "ProjectMedia" ADD CONSTRAINT "ProjectMedia_mediaId_fkey" FOREIGN KEY ("mediaId") REFERENCES "Media"("id") ON DELETE RESTRICT ON UPDATE CASCADE;
ALTER TABLE "Service" ADD CONSTRAINT "Service_heroMediaId_fkey" FOREIGN KEY ("heroMediaId") REFERENCES "Media"("id") ON DELETE SET NULL ON UPDATE CASCADE;
ALTER TABLE "Service" ADD CONSTRAINT "Service_thumbnailMediaId_fkey" FOREIGN KEY ("thumbnailMediaId") REFERENCES "Media"("id") ON DELETE SET NULL ON UPDATE CASCADE;
ALTER TABLE "Service" ADD CONSTRAINT "Service_ogImageId_fkey" FOREIGN KEY ("ogImageId") REFERENCES "Media"("id") ON DELETE SET NULL ON UPDATE CASCADE;
ALTER TABLE "Testimonial" ADD CONSTRAINT "Testimonial_mediaId_fkey" FOREIGN KEY ("mediaId") REFERENCES "Media"("id") ON DELETE SET NULL ON UPDATE CASCADE;
ALTER TABLE "Client" ADD CONSTRAINT "Client_logoMediaId_fkey" FOREIGN KEY ("logoMediaId") REFERENCES "Media"("id") ON DELETE SET NULL ON UPDATE CASCADE;
ALTER TABLE "NavigationItem" ADD CONSTRAINT "NavigationItem_navigationId_fkey" FOREIGN KEY ("navigationId") REFERENCES "Navigation"("id") ON DELETE RESTRICT ON UPDATE CASCADE;
ALTER TABLE "NavigationItem" ADD CONSTRAINT "NavigationItem_parentId_fkey" FOREIGN KEY ("parentId") REFERENCES "NavigationItem"("id") ON DELETE RESTRICT ON UPDATE CASCADE;
ALTER TABLE "SiteSetting" ADD CONSTRAINT "SiteSetting_logoMediaId_fkey" FOREIGN KEY ("logoMediaId") REFERENCES "Media"("id") ON DELETE SET NULL ON UPDATE CASCADE;
ALTER TABLE "AuditLog" ADD CONSTRAINT "AuditLog_userId_fkey" FOREIGN KEY ("userId") REFERENCES "User"("id") ON DELETE SET NULL ON UPDATE CASCADE;
