import { deleteTestimonial, saveTestimonial } from "@/app/admin/actions";
import { EmptyState, PageHeader, StatusBadge } from "@/components/admin/AdminPrimitives";
import { hasDatabaseUrl, prisma } from "@/lib/db/client";

export default async function TestimonialsAdminPage() {
  if (!hasDatabaseUrl()) return <section className="admin-content"><PageHeader eyebrow="CONTENT / TESTIMONIALS" title="Testimonials" description="No testimonials are fabricated; this editor is ready when an approved database is connected." /><EmptyState title="Database not configured" description="Set DATABASE_URL to manage verified testimonial records." /></section>;
  const [items, media] = await Promise.all([prisma.testimonial.findMany({ orderBy: { order: "asc" } }), prisma.media.findMany({ where: { mediaType: "IMAGE" }, select: { id: true, filename: true }, take: 100 })]);
  return <section className="admin-content"><PageHeader eyebrow="CONTENT / TESTIMONIALS" title="Testimonials" description="Only use approved quotes and identities. Empty collections remain hidden publicly." /><div className="admin-editor-grid"><form action={saveTestimonial} className="admin-card admin-content-form"><h2>Add testimonial</h2><label>Quote<textarea name="quote" rows={6} required /></label><label>Person<input name="person" /></label><label>Role<input name="role" /></label><label>Company<input name="company" /></label><label>Avatar / logo<select name="mediaId"><option value="">No media</option>{media.map((item) => <option key={item.id} value={item.id}>{item.filename}</option>)}</select></label><input type="hidden" name="enabled" value="false" /><label className="admin-check"><input name="enabled" type="checkbox" value="true" defaultChecked /> Visible</label><button type="submit">Save testimonial</button></form><div className="admin-card"><h2>Verified records</h2>{items.length ? <div className="admin-record-list">{items.map((item) => <article key={item.id}><div><strong>{item.person || "Unnamed testimonial"}</strong><span>{item.quote}</span></div><StatusBadge value={item.enabled ? "ACTIVE" : "HIDDEN"} /><form action={deleteTestimonial}><input type="hidden" name="id" value={item.id} /><button>Delete</button></form></article>)}</div> : <EmptyState title="No testimonials" description="The public site will continue without a testimonial section." />}</div></div></section>;
}
